### ISSUE TITLE
Need favicon for browser

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#100]
Once have logo, make into favicon so we have a browser tab icon.
- Possibly do interim version that's not finished logo?
- Related to #85

**Comment by walshbr** [comment]
@amandavisconti - check out the favicon on #409 PR? it's an initial pass at one - just a cropped white rotunda. If that works we can either close this issue or move it to rainy day as a part of a distant future when we have time to design a more personal/permanent one.
