### ISSUE TITLE
Make sure https://scholarslab.lib.virginia.edu/feed.xml still works (for folks following, DH Now)

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#1025]

**Comment by jeremyboggs** [comment]
This appears to be working for me, both on the current site and on the locally-generated site. Are you seeing something different, @amandavisconti?

**Comment by amandavisconti** [comment]
No, I just wanted to check after changing deployment stuff—but on reflection, I don't see how that could mess with it, so I'll close this (DH Now just restarted, so extra wanted to make sure our feed works so it gets pulled in ther)
