### ISSUE TITLE
Add YAML field to events for registration link

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#1028]
For consistency and to make it easier to display and style, we should consider adding a YAML field to events for any registration link we wish to display.

**Comment by amandavisconti** [comment]
Implemented with https://github.com/scholarslab/scholarslab.org/commit/b69d5fc6c0c543274f22e72b2ed28f2b025ea901 and GradCamp event updated to use.
Added to event creation documentation
