### ISSUE TITLE
Create an Events Archive page

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#1029]
To better feature upcoming events that are both Scholars' Lab and affiliated or of interest to our community, we should consider moving the substantial list of past events to a separate Events Archive page.

**Comment by amandavisconti** [comment]
My [recent commit](https://github.com/scholarslab/scholarslab.org/commit/4148efaef63d74b8f9aaea73f7fdc7b78671c2c2) finished work on this:
- Split /collections/_events into 2 folders:
      1. _events (upcoming events go here; keeps "recent events" section that is only events from that academic year that have already happened, ie haven't been moved yet to /_past-events because we only do that each summer; this means those events don't disappear from site once not upcoming + not moved to /_past-events folder)
      2. _past-events (manually move events from past years here)
- Used config to make events moved to /_past-events keep their original URL
- Added Event Archive (/event-archive_ dropdown item to nav Events top-level item
- Added links on /events and /event-archive to the other page

To do (I am moving these to other tasks):
- [ ] Schedule manual annual events move to /_past-events folder
- [ ] Update events documentation about which folder to use; and filename pattern

Might be preferable to have /collections/_events, with /_past-events inside /_events? I couldn't get that to work when I tried, and isn't clear whether that's better organization.
