### ISSUE TITLE
Remove photos for students when they aren't added yet

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#1036]
Vs /people looking like:
![Screenshot 2024-08-10 at 12 16 43 PM](https://github.com/user-attachments/assets/233d553e-1493-4c22-ad2f-8a3ba2c2302d)

**Comment by jeremyboggs** [comment]
I removed this, and plan to simply not display photos until all our students have photos.

**Comment by amandavisconti** [comment]
Perfect!

**Comment by amandavisconti** [comment]
Done!
