### ISSUE TITLE
Determine links that'll be present in the topnav bar

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#107]
### Context
- Need to decide what links are most important for people to see on load
- Probably ask @lam2c and @rondauva about this

### Associated Product Ticket
- #101, #103 (sort of)

**Comment by jeremyboggs** [comment]
@amandavisconti @lam2c @rondauva  Let's update the description of this ticket with a list of pages we want to appear in the navbar, in the order we want them appear, so @kbdonnally can update the nav and close this ticket.

**Comment by amandavisconti** [comment]
1st pass at top-nav dropdowns—NOT final. Shooting for 5? top nav links, but still need to think through how to arrange the other pages.

**About**
- FAQ (subsection on About page?)
- People
- Hours & Spaces
- Charter
- Accessibility
- Colophon

**Blog**

**Scholarship** (work? projects? something that captures hunks of activity that aren't just research)
- Lab (subsection of scholarship page for new rough ideas)
- Publications (???)

**Makerspace**
- Makerspace 3D Printer Calendar

**Events**
- Past events

**R&D**

**Spatial Technologies**
- Geospatial Services
- Cultural Heritage Informatics

**Student Opportunities** (disambiguation page, currently titled Graduate Fellowships and Opportunities)
- Professional Development
- Praxis Program Fellowships
- Digital Humanities Prototyping Fellowships
- Digital Humanities Fellows Program
- Scholars' Lab GIS Technician
- Cultural Heritage Informatics Internship
- Makerspace Technologists
- Guest DH Workshop Teaching at W&L

**Comment by amandavisconti** [comment]
I think I'd like About, Blog, Events, and Scholarship (or whatever we call research/projects/work) in the topnav, but I'm not sure how to arrange the remaining needs into the one remaining top nav slot (or is 6 top nav links okay?)

**Comment by amandavisconti** [comment]
1. About
2. Blog
3. Scholarship
4. Events
um (to be edited)

**Comment by kbdonnally** [comment]
@amandavisconti what should R&D, Pedagogy, and Scholarship link to? Those pages don't exist right now. Or, more specifically, is there a list of links to pages that _do_ exist right now that you'd like to use? We won't be able to make a bunch of new pages before we show it at the staff meeting, but the top nav needs to make sense re. what links people see us displaying prominently. (I hope this made sense.)

**Comment by amandavisconti** [comment]
yes! how about:
research.html for scholarship
student-opportunities.md for pedagogy
lab.html for R&D
