### ISSUE TITLE
Design /pages to look acceptable on mobile devices

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#110]
# Short term
- [ ] Check whether some /pages having different layouts indicated in YAML ("default" vs. "page") impacts or solves the issues below
- [ ] fix appearance of all static /pages at mobile sizes & window dragging
- [ ] homepage loading (background of hero text either as loading too slowly, or is just coded to only appear partially with the correct purple background vs. white)

# Long term
- [ ] Landing pages are just more basic versions of full-size right now, which isn't ideal given size of mobile traffic now. Spend time styling them en masse once have a few pages otherwise finished

**Comment by amandavisconti** [comment]
Scheduled time to work on this 6/3

**Comment by amandavisconti** [comment]
closing as antiquated issues; made a note in #968 to test for mobile
