### ISSUE TITLE
Standardize styles for elems like page titles, subtitles, body text, etc.

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#111]
### Context
1. What should the feature do?
- Define all of these separately so you're not redeclaring them unnecessarily
- Use semantic HTML elements as selectors with styles, since right now everything is divs
2. When and where should the feature appear?
- As its own SCSS file, probably

**Comment by kbdonnally** [comment]
Should use 8.33% padding per side everywhere on text-heavy pages; isn't very readable otherwise. (Will upload iOS photos demonstrating issue when have a chance. Particularly relevant on blog.)

**Comment by amandavisconti** [comment]
@kbdonnally Will make your comment on padding a separate issue, then moving this to post-release as it isn't a dealbreaker for launch

**Comment by amandavisconti** [comment]
Closing; this can come up naturally in retheming, or not
