### ISSUE TITLE
Convert divs into semantic HTML elements where fit

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#112]
### Context
1. What should the feature do?
- Use more specific elements like `<h1>` and `<p>` rather than `<div>` for accessibility and SEO
- Have used class names thus far as standardized descriptors, which is fine for production but not deployment
- Will also make class names do less heavy lifting, which means less repetition
2. When and where should the feature appear?
- Towards the end of site writing, when going through for edits/standardization
### Associated Product Ticket
- Coordinates with #111

**Comment by kbdonnally** [comment]
*NB: definitely do entire feature branch at end where you're just focusing on this; no actual style appearances should be edited during this process.*

**Comment by jeremyboggs** [comment]
@kbdonnally We might devote just a day to this, where we pair program and review each page/template and discuss options.
