### ISSUE TITLE
Link to and eventually incorporate the calendar

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#117]
### Context
1. What should the feature do?
- Link to it by launch
- Incorporate linked calendar with `<iframe>` eventually so that it only has to be updated in one place
2. When and where should the feature appear?
- Link: ASAP
- Incorporation: lower priority for now, but will really help @lam2c et al. long term re. maintenance.
### Associated Product Ticket
- #108 
### Process
1. Potential Impact on Code or Other Features
- Calendar itself needs to work first
- Also need to figure out how to incorporate iframe/widget thingie

**Comment by kbdonnally** [comment]
Also adding `FUTURE` label somewhat paradoxically - is b/c of later change in incorporation method.

**Comment by jeremyboggs** [comment]
@kbdonnally Can we update this ticket to describe _where_ the calendar should appear? Which page, and where on the page?
