### ISSUE TITLE
Big picture list of topic pages to complete

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#119]
### Big Picture
*List of pages, to be checked off as they're completed.*
- [ ] About
- [ ] Accessibility
- [x] Blog
- [ ] Charter
- [ ] Colophon
- [x] Events
- [ ] Hours And Spaces
- [ ] Lab
- [ ] Makerspace 3D Printer Calendar
- [x] Makerspace
- [ ] People
- [ ] Research
- [ ] Search
- [ ] Sitemap
- [x] Spatial Technologies

*NB: Taken directly from `pages/` directory filenames, so list is subject to change.*

**Comment by amandavisconti** [comment]
(I'm assuming this is for page design / other purposes than content—I'm going through page content on every static page over in #213)

**Comment by kbdonnally** [comment]
Too broad at this point
