### ISSUE TITLE
Dynamically update our hours based on library/university announcements

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#121]
Determine if its possible to display library and university closings on our own site. And, determine possibilities for updating our own hours dynamically based on feeds from the library and university.

This feature would require both a reliable feed or API we could use and a list of ways our own operations and schedules changed as a result of closing.

**Comment by walshbr** [comment]
This might be the closest thing to a reliable listing that I know of - http://statusboard.uvaemergency.virginia.edu/

But not sure if that's something we could integrate with.

**Comment by amandavisconti** [comment]
This is implemented (both /use-the-lab and /makerspace hours pull from LibCal)
