### ISSUE TITLE
Add description to beginning of /research/ page

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#126]
### Context
1. What should the feature do?
- Provide summary in 1-2 sentences of what the purpose of the `/research/` page is
- Good to have this appear before gallery starts, especially on mobile since only 1 will be able to fit on screen at a time
  - There are 22 projects total so we shouldn't ask people to explore them all without giving a summary of what we want them to explore
   - NB: the gallery summaries are helpful, but distinct from this feature request.
2. When and where should the feature appear?
- Below the main title on `/research/`, within the next week.
### Associated Product Ticket
#125 - both concern `/research/` content
### Process
1. Potential Impact on Code or Other Features
- We should make sure we have something like this for all major pages. @kbdonnally make a profile of all pages to see which ones we do and don't have that for, or if they're not relevant for some pages.
2. Suggested Implementation
- Determine w/ @lam2c and @rondauva tomorrow morning (3/27) who will be responsible for making sure this gets done w/in the next week
- After actual text exists, send to @kbdonnally whereupon she'll add it to the `/research/` page template.
  - Right now there's just dummy text there.

### Expected Result
- People who don't know much about what the URL `scholarslab.org/research/` might entail are more confident about what they'll experience if they start scrolling down the rather long gallery
- Hopefully entices people who maybe would have clicked away, but also it's just a nice thing to have as a user even when you do know about something - it's a chance for us to say "this is what *we* see this page as doing"

**Comment by amandavisconti** [comment]
Related issue: https://github.com/scholarslab/scholarslab.org/issues/33

**Comment by amandavisconti** [comment]
Research page draft summary:

> Scholarship is one part critical thinking (research, writing, coding, building, designing, experimenting, play…) and one part communication (traditional publishing and other forms of “making public”, teaching, open source code, other ways for your intellectual community to learn from and build on your work). This page shares a sampling of the Scholars’ Lab scholarship in its many states and forms, from incipient ideas to projects with their own laptop stickers.
