### ISSUE TITLE
Highlight "What we're working on now" in Research

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#127]
### Context
1. What should the feature do?
    - Indicate on the Research page which projects are under active development for the next few months (certain span of time).

2. When and where should the feature appear?
    - Research Page
    - Possibly the home page.

### Associated Product Ticket

- #37 
- #125 
- #126 

### Process
- Suggested Implementation
    - Might store this as an array in the `_config.yml` or a data file, to update this list separately from individual research files.

**Comment by amandavisconti** [comment]
Combined into #376
