### ISSUE TITLE
Structure/style for research project preview

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#132]
### Context
- Finish template & styles for how individual events appear in the `/research/` page display
### Associated Product Ticket
#130, #82, #125
### Process
- Get year information from @lam2c and/or @rondauva 
- Finish SCSS for page
### Expected Result
- Research (/research/) page will be done!

**Comment by rondauva** [comment]
Year info is in a google doc at https://docs.google.com/document/d/1s15m1r_LeTxdxo7uswXjIyFFmmPum2Pl1DTs3d8Oj_s/edit?usp=sharing

**Comment by rondauva** [comment]
re: sorting project previews

Can we do the "Library thing" and sort the projects by dropping off any definite article ("the") in the project's title? Maybe I'm just an old fuddy duddy, but I automatically look for the Falmouth project in the Fs, not in the Ts, for example.
