### ISSUE TITLE
Fellowship (singular) page layout/style

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#140]
### Context
- This is the detail view for the fellowships highlighted on the `/fellowships/` page. It gives all the due date info, describes the fellowship, and highlights contact info if people have questions.
### Associated Product Ticket
#139, #396 
### Process
1. Potential Impact on Code or Other Features
- There are several distinct sections in the fellowship postings (eligibility, description, due date) so I probably will hard-code HTML for all of them instead of keeping them as Markdown.
2. Suggested Implementation
- Grab rendered code off of current website -> strip it, add your own classes, rearrange structure if needed
- Also there's a rough draft of this in your patterns repo as an example of a text-based page
### Expected Result
- Cool/interesting-looking fellowship postings that still maintain a) info clarity and b) professionalism.

**Comment by amandavisconti** [comment]
@kbdonnally  I might be able to mock this up using your existing work on other pages, if you want to spend time on other tasks I can't help with as well?

**Comment by amandavisconti** [comment]
Moving this to Rainy Day milestone: #396 makes sure these links point to pages, but we can wait to give these pages better design/structure.
