### ISSUE TITLE
Review, remove redundant headings in posts

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#147]
### Context
Some posts duplicate the `title` in the content of the post, as a Markdown-encoded H1. This means the title is printed twice on the post page.

### Process
- Review posts to determine the extend of this issue;
- Depending on the number of affected posts, either write a script to  automagically remove those redundant headings, or remove by hand;
- Add updated posts in a single commit.

### Expected Result
- No more too many headings.

**Comment by amandavisconti** [comment]
Working on this locally.
