### ISSUE TITLE
Review pages for markdown syntax issues

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#148]
### Context
Converting content from WP to Jekyll/Markdown resulted in some incorrectly-formatted markdown. let's review and fix.

**Comment by amandavisconti** [comment]
@jeremyboggs Do you remember if you saw these markdown bugs before or after your last content migration? (If after, do you have an example of what kind of thing to look for, or is this just scanning the rendered HTML to look for formatting weirdness?)

**Comment by jeremyboggs** [comment]
@amandavisconti I don't remember. @kbdonnally and I disucssed possibly adding a persistent message to each page indicating that 1) we've migrated to a new platform, and 2) we're working to correct errors as a result, and if someone encounters something, to get in touch with us. So, think we could give our static pages and recent posts a good review, but don't think we need to review all 10+ years worth of blog posts.

**Comment by jeremyboggs** [comment]
@amandavisconti I will say I've encountered stuff that could be formatted _better_, but this is more of a nice-to-do, and not really a blocker for a release.

**Comment by amandavisconti** [comment]
@jeremyboggs @kbdonnally Would it be useful for me to add text to the top (or bottom?) of the older blog posts I'm not going to look through?

I could search for the --- ending the front matter and insert something like this on the following line:

<div ID="migration-alert">We migrated this website to a new platform, and are working to correct formatting errors in older blog posts as a result. If you encounter an error, please send an email to <a href="mailto:scholarslab@virginia.edu?subject=Found a blog formatting error">scholarslab@virgnia.edu</a>. Thanks!</div>

**Comment by jeremyboggs** [comment]
@amandavisconti I'd recommend writing some sort of message, and let @kbdonnally figure out the best place to put it. Offhand, I was thinking it'd be a persistent thing on all pages for a while. We could save it in the config and add it where needed.

**Comment by amandavisconti** [comment]
I created #250 for me to check display formatting on the last year's blog posts, and #251 for @kbdonnally to add a migration-weirdness alert.
