### ISSUE TITLE
"Subtitle"/intro text for blog

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#161]
### Context
1. What should the feature do?
- Add a sentence or so of intro text to the blog
- Similar to intro text on research page & events page
2. When and where should the feature appear?
- When: up to content team, but before May 14th and ideally before April 30th
- Where: in `pages/blog.html` under `.blog-header__subtitle` if blog layout has already been merged into master, *or* in `pages/fake-blog.html` (same place in doc) if not.
  - Doesn't really matter as long as commits are clearly labeled so we can find the text
### Associated Product Ticket
- #104, #130, #133 
### Process
- Would be awesome for this to be done sooner rather than later, so the design reflects the *actual* rather than *assumed* (read: dummy text) composition of the intro text.
### Expected Result
- Concise explanation of what the user is looking at when they load our blog page.
- An environment where we direct the context of the blog's content, rather than whatever happens to be the most recent post giving the user their first impression of the blog's content as a whole.

**Comment by amandavisconti** [comment]
“Our thoughts, from rough new ideas to polished arguments. Scholars’ Lab team and collaborators write about their experimental [scholarship](link to scholarship/research/whatever page?) around humanities and culture.”
