### ISSUE TITLE
Consider LFS for site images & other media

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#162]
Right now, posts and pages are hotlinking to images and other assets currently in our `wp-content` directory. Let's look into using [Github's Large File Storage](https://git-lfs.github.com/).

**Comment by amandavisconti** [comment]
We should try to do this before the public release, because we'll probably take down the WP site around then and I don't want to forget this breaks the hotlinks.

**Comment by mossiso** [comment]
I'm inclined to say don't use LFS unless we actually want to track the changes to that file, but it could make it easier to manage them (making sure they get to the production server, etc...)

**Comment by jeremyboggs** [comment]
Closing as wontfix. Addressing issues discussed here in #12.
