### ISSUE TITLE
Add/update inclusivity statement

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#166]
### Context
- Initial prompted by the need to encourage peopel to attend our events and workshops regardless of whether their own department/discipline aligns with the topics of a given event.
- E.g. You are welcome regardless of your degree, expertise.

### Tasks
- Writing actual content, either a simple sentence or two or a longer paragraph. (@lam2c @rondauva @amandavisconti @jeremyboggs)
- Adding and displaying that content on various views as needed (@kbdonnally)
### Expected Result
- Language in specific places (The Events listing and individual events pages) welcoming attendance regardless of training or degree.

**Comment by amandavisconti** [comment]
Some draft ideas (let me know if any of these fit, and I can polish them further):

These events are for _you_, regardless of your background or place on grounds or off. Sometimes the most exciting ideas come from learning outside your normal area!

Are you curious about the intersections of art, culture, crafting, making, preservation, and technology?

Curious about trying out some hands-on ways of advancing your scholarship? Come experiment alongside peer scholars in a judgement-free, no-prior-knwoledge-needed environment.

Do you enjoy thinking hard about something (fan fiction, dance, making GIFs, activism) that doesn't get treated as part of your job? We recognize scholarship as critical thinking that you share with others so they can learn and build off that, regardless of method or topic. Bring us what makes you curious or passionate, and we'll help you take your next steps.

We've got a wide mix of expertise, and everyone here is a novice at something. Come share _your_ knowledge and let us help you learn your next new ____ [method?]
