### ISSUE TITLE
images for research projects

### ISSUE THREAD

**Issue by rondauva** [scholarslab/scholarslab.org#167]
### Context
1. What should the feature do?
provide visual marker for each project

2. When and where should the feature appear?
on the research page

### Associated Product Ticket
[136](https://github.com/scholarslab/scholarslab.org/issues/136)

### Expected Result
set of images done to Katherine's requested specs, one for each research project

**Comment by kbdonnally** [comment]
Hey @rondauva! I've been trying to work on the research design and have discovered I can't reconcile a design that's both stable and different from our current design without having the new images. Would it be possible to have those ready by Tuesday or Wednesday? No worries if they're not permanent or if they're different from the original pictures; just something that plausibly works vibe-wise should be fine for a rough design. (Also, no pressure if this isn't plausible by time requested.)

**Comment by rondauva** [comment]
Hey @kbdonnally No worries. I'll work on these today. I cannot find anywhere in my notes what you requested re: size of these new images or their aspect ratio. Can you please remind me? Thanks!
