### ISSUE TITLE
Account for multiple authors

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#17]
Update templates to allow for specifying multiple authors on blog posts. It should be easy enough to specify multiple authors in the post YAML, like so:

```yaml
---
author:
  - sarah-berkowitz
  - james-ascher
---
```
 Our templates for displaying post author(s) should change to account for this.

**Comment by walshbr** [comment]
Can this just be an array of author slugs instead of a single one? Then we'd need some logic when displaying the title to check whether the contents of the author field will be a single author or an array and respond accordingly.

**Comment by jeremyboggs** [comment]
> Can this just be an array of author slugs instead of a single one?

Yes! In fact, keying it in like the example essentially turns `page.author` into an array. Already doing this as of 28abc29.
