### ISSUE TITLE
Add Pagination to Blog

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#170]
Add pagination to the list of blog posts.

**Comment by jeremyboggs** [comment]
Adding this doubles the build time.

**Comment by jeremyboggs** [comment]
I spoke too soon: Adding this does double the build time, but the jekyll-paginate gem doesn't work, and is no longer supported. Looking into using [jekyll-paginate-v2](https://rubygems.org/gems/jekyll-paginate-v2).

**Comment by amandavisconti** [comment]
@jeremyboggs needs to merge new stuff and PR (or... something?)

**Comment by amandavisconti** [comment]
@jeremyboggs I vaguely remember from our milestone review—do you have some work toward this (adding pagination to the blog) on a branch ready to merge in?

**Comment by jeremyboggs** [comment]
@amandavisconti There is a branch, and a pull-request, for this. Should be reviewed.
