### ISSUE TITLE
Decide on dev workflow once this repo = our production site

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#171]
We're currently building the site on github pages. Let's discuss options for deploying this on our own server.

**Comment by amandavisconti** [comment]
Options I can think of:

1. Use GitHub Pages -hosted site as development space for drafting posts, previewing posts before publication, trying out things that GH's rules for Jekyll plugins allow
2. [Some workflow] for moving posts that are ready for publication & preview correctly to the production site, e.g.
- tweeting links
- sharing a link on staff & UVA Library Slack channels
3. A second dev site, hosted on our server, for testing out stuff that GH Pages won't let us test out there

**Comment by walshbr** [comment]
It's a bit wonky to implement retroactively, but I just implemented this over the weekend - http://joshfrankel.me/blog/deploying-a-jekyll-blog-to-github-pages-with-custom-plugins-and-travisci/. Allows you to have custom jekyll plugins built through GitHub. Pretty clean though once your have the branching strategy set up. But sounds like you're already committed to deploying on your own server.

**Comment by amandavisconti** [comment]
I'm reassigning this to @jeremyboggs @mossiso—let me know if that's incorrect. (Sounds like you have a nice git-flow thing worked out?)

**Comment by amandavisconti** [comment]
Regardless of if we eventually host on our own servers instead of GitHub's, could we decide pre-release on how to make
1. dev/design updates to the site (separate repo? linked how?)
2. post/page content changes (branch, PR, merge?)

**Comment by walshbr** [comment]
@jeremyboggs might have thoughts from a best practices perspective, but I think we should just do branch/PR/review/merge for each and all.

**Comment by amandavisconti** [comment]
Driving it like I stole it, I hereby declare branch/PR/review/merge as our release practice. Will create a separate Rainy Day issue for if/when folks want to do something different—I would e.g. like to have a live development site eventually. Am noting in my documentation this will be our process, at least for now.
