### ISSUE TITLE
Update filenames of images listed in YAML of _research/ files

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#173]
### Context
1. What should the feature do?
- Re-label all of the YAML in _research/ to reflect updated image names
2. When and where should the feature appear?
- When: ASAP, hopefully before 5/3
- Where: YAML of each research project, located in `_research/projectname.md`.
- New images aren't in the main research img directory in the `research` branch as I'm writing this, but will be shortly. Slack Katherine if they're not!
- *Edit: the default image directory is `assets/img`, and each collection with images has a correspondingly named directory. So, research images are located in `assets/img/research`. Thanks @amandavisconti for pointing this out!*
### Associated Product Ticket
#132, closes #167
### Process
1. Potential Impact on Code or Other Features
- Exact filenames are important so that the images for projects, both on their individual page and the research gallery page, are able to load.
- Katherine can finish designing the research page once these are loaded
2. Suggested Implementation
- Current: `preview-img: imgname.ext`
  - Need:  `banner-img: imgname.ext` and `thumb-img: imgname.ext`
  - Where: lines 5-6 of each research document. All YAML is in same order in them. (Current variable is on line 5.)
### Expected Result
- Pretty research images of multiple sizes accessible through Liquid variables

**Comment by amandavisconti** [comment]
Amanda will do this 5/9 2pm.

**Comment by amandavisconti** [comment]
Amanda will do this 5/3 10:30am
