### ISSUE TITLE
Workflow to tweet after publishing a post

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#18]

**Comment by jeremyboggs** [comment]
Can you...say more? Is this related to #29?

**Comment by walshbr** [comment]
No - #29 is a twitter feed embedded on the site itself. This issue would be about tweeting posts in particular after they are published - the way the wordpress social media broadcasting is meant to be doing.

**Comment by jeremyboggs** [comment]
Could see us writing a `rake publish` task that would publish a blog post and send a tweet out through the API? Might look at twitter ruby libraries?

**Comment by nabsiddiqui** [comment]
Hey @jeremyboggs and @walshbr, I just saw this as I was working on updating my own website to Jekyll and looking at other DH examples.  The fastest way to do something like this is to take the XML feed and tweet it out using a service that tweets based on the RSS feed.  I think IFTTT can do it.

**Comment by jeremyboggs** [comment]
👍 @nabsiddiqui Worth looking into, for sure. Thanks!

**Comment by jeremyboggs** [comment]
If we can't address this by our public launch, we should at least be prepared to document or help folks with sharing these links.

**Comment by amandavisconti** [comment]
Let's wait on this for now–some confusion about when we're announcing the site.

Once that's cleared, perhaps we could do a mix of IFTTT as you suggest, plus I could schedule myself to do a weekly quote-tweet of any new blog posts tweeted during the previous week, adding any username/author, description, and #ICYMI.

**Comment by walshbr** [comment]
Totally - just wanted us to resurface this since it's basically ready to go.

**Comment by walshbr** [comment]
This is hooked into IFTTT now. It will also post to the relevant slack channel when we post a new blog entry.
