### ISSUE TITLE
Newsletter signup

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#185]
Give @kbdonnally the embed code to place the newsletter field on the homepage.

**Text about the newsletter pulled from the footer issue (#48):**
Ronda: @lam2c requests that the sign up for email announcements gather more information: name, department (via dropdown) or non uva, affiliation (grad student, undergrad, faculty, staff, etc.)
Jeremy: @rondauva @lam2c We need to determine what Mailchimp (which is what we use for newsletter registration) will accept on a form submit. Can one of you do this?
If it won't let us gather those things, then we need to discuss whether this feature is important enough to explore other code and/or newsletter options.

**Comment by rondauva** [comment]
Mailchimp PAID users can create a custom form, on which we could include the data that @lam2c wants to collect. As free user, there's no way to do this.

**Comment by amandavisconti** [comment]
Let's discuss fancier Mailchimp options. For now, I added a Mailchimp embed code (same thing as we're using on the old site and will add signup info to the same place) in #227.
