### ISSUE TITLE
Clean up data

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#19]
Lots of data cleanup that needs to happen on various parts of the site.
- [ ] - people
- [ ] - projects
- [ ] - posts especially re: podcasts and image links

**Comment by rondauva** [comment]
I'll start on cleaning up People today.

**Comment by walshbr** [comment]
Mentioned this on the slack channel @rondauva -

> as far as data goes, the research projects are pretty stable. people is still missing stuff, so might need to be regenerated. events are done. posts need a lot of manual cleanup, I think, but should be good for that whenever.

So people I think might get regenerated and lose any clean up. So I might start with projects and events. Then we can do posts, but we need to figure out how we're going to work with the podcasts. Might be worth a conversation about what specific things need to be cleaned up so that you know what you're looking for (though I'm sure you'll find other stuff I'm not expecting).

**Comment by rondauva** [comment]
Thanks Brandon, I'll work on projects then.

**Comment by rondauva** [comment]
Projects have collaborators and links, except for spatial-search-and-delivery.md, solrmarc.md, and thl-place-dictionary.md. I added links to the the geoinst and thdl files, but I had no idea how to list collaborators on those. I have no idea who worked on solrmarc. When I can find out this info, the list will be complete.

**Comment by amandavisconti** [comment]
Awesome work! I moved the remaining pieces into #35 and will finish them as part of my content migration work.
