### ISSUE TITLE
Person page: if staff member not current, denote on their page

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#192]
### Context
1. What should the feature do?
- Make it clear who is and is not currently staff
- Right now the person page doesn't say anything to indicate whether or not the person is currently there, which is confusing/misleading
2. When and where should the feature appear?
- In `_layouts/people.html` by May 22nd
- Am initially just going to add the word "Former" in front of or after their job title, and content team/other staff w/ longer view on this can adjust from there
  - @amandavisconti @rondauva @jeremyboggs @lam2c 
### Associated Product Ticket
#40

**Comment by amandavisconti** [comment]
I'm updating this in #40 so will close this ticket.
