### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#2]
Add better ways to search/browse content on the site.

**Comment by jeremyboggs** [comment]
Possible solution - https://github.com/slashdotdash/jekyll-lunr-js-search

**Comment by amandavisconti** [comment]
I worked on this two days but didn't get anything I liked working, so I'll come back to this in the future but anyone should feel free to work on this instead

**Comment by ZoeLeBlanc** [comment]
Search is merged into master. Still needs a few tweaks in our meta-data but everything with the search is working.
