### ISSUE TITLE
Search should include all content

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#206]
The search feature currently only indexes blog post content. Let's update the search indexing to include all content, possibly add ways to sort by posts or pages.

**Comment by jeremyboggs** [comment]
Related to #47.

**Comment by amandavisconti** [comment]
Is the current search of posts only okay for public launch, or should we keep this part of the pre-release milestone?

**Comment by jeremyboggs** [comment]
@amandavisconti It's OK with me, but then again I've been OK with the Scholars' Lab site not even having a search form for five years now. :)

**Comment by jeremyboggs** [comment]
This was addressed in 358020b.
