### ISSUE TITLE
Add Beth's SVG on Hours & Spaces page

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#210]
Beth's diagrams need incorporating

**Comment by kbdonnally** [comment]
Didn't realize current Hours & Spaces page was so robust so this is somewhat redundant, but add the SVG on a rainy day.

**Comment by amandavisconti** [comment]
Asked in #slab-org 4/16/2019 whether this means a duplicate of the current interactive homepage floorplan, or some other image I don't know of

**Comment by amandavisconti** [comment]
Added front page interactive diagram to hours-and-spaces as well (this meant converting it, as some of the other /pages have been, to .html instead of .md). Noticed floorplan breaks at some smaller browser widths, but created separate #732 to address this.
