### ISSUE TITLE
Hours & spaces data

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#222]
- [x] One data file for keeping common area, makerspace, classroom, etc. hours
- [ ] Insert in places they're needed (FAQ, Spatial Tech page)
- [x] Remove hours-and-spaces apge
- [x] Remove link to hours-and-spaces page on about.md

**Comment by jeremyboggs** [comment]
Completing work on this in the [hours-spaces-data](/scholarslab/scholarslab.org/tree/hours-spaces-data) branch

**Comment by amandavisconti** [comment]
Laura really wants this

**Comment by amandavisconti** [comment]
check with alura on pages, spaces this needs to go; ideal data structure for this

**Comment by amandavisconti** [comment]
Looks like this is done
