### ISSUE TITLE
Better text for link accessibility

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#226]
Review all links on the site to ensure the link text itself is unique and descriptive of the actual content at the destination.

Avoid using phrases like "click here"; Not only is this ableist (some folks don't click), but pages with multiple instances of this phrase will be unhelpful for folks who use screen readers.

See [WebAIM's techniques for accessible links](https://webaim.org/techniques/hypertext/link_text) for helpful approaches.

**Comment by jeremyboggs** [comment]
Adding a bunch of folks to just alert you to look for these things when adding/editing content.

**Comment by amandavisconti** [comment]
look for [here] and other common, and then close ticket

**Comment by amandavisconti** [comment]
keep links to 4 or less words

**Comment by amandavisconti** [comment]
Searched for & fixed the following in all non-post content:
[here]
[click here]
[more]
[link to
[read more]
