### ISSUE TITLE
Replace Makerspace calendar with libcal

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#229]
Because Google calendar is obnoxious, and doesn't display correctly in non-Chrome browsers.

**Comment by jeremyboggs** [comment]
Related to #973

**Comment by amandavisconti** [comment]
Is this already accomplished? Looking at the makerspace layout (at least in the /realignment branch), the section displaying the week's schedule appears to maybe draw from LibCal already?

<div id="makerspace-hours" class="maker-hours__title">Open Hours and Access</div>
    <script src="[//ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js](view-source:https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js)"></script> 
    <script src="[**https://cal.lib.virginia.edu/js/hours_grid.js?002**](view-source:https://cal.lib.virginia.edu/js/hours_grid.js?002)"></script> 
    <div id="s-lc-whw2093"></div> 
    <script>
      **$(function(){ 
        var week2093= new $.LibCalWeeklyGrid( $("#s-lc-whw2093"), { iid: 863, lid: 2093, systemTime: false }); 
      });**
    </script>

**Comment by amandavisconti** [comment]
Whatever is being used, it does display correctly in Chrome. Closing this. Please reopen if I'm incorrect and this still needs to be done!
