### ISSUE TITLE
Create UVA Library homepage section

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#230]

**Comment by amandavisconti** [comment]
@kbdonnally I've drafted some text for a homepage section about the Library—would you be willing to put this in, since I'm not sure how to appropriately bedeck it with HTML/CSS?

THE LIBRARY'S LAB
We're part of the UVA Library's mission to provide equitable access to learning to everyone, and we're proud that librarian superpowers are part of our toolkit! Find out about the many ways we collaborate with and depend on our amazing Library colleagues <a href="http://scholarslab.org/library">here</a>, or <a href="http://lib.virginia.edu">jump to the UVA Library's main website</a> to find out more about the whole Library.

**Comment by kbdonnally** [comment]
@amandavisconti I know this is suuuper late response, but do you still want me to add this? Am happy to if so, or you're welcome to add and I'll fix the layout. Just let me know where on the page you'd like it if I should add it!

**Comment by kbdonnally** [comment]
NB: am referencing "organization of homepage sections" from info architecture doc to organize homepage 2.0, so by "where" I mean in relation to those sections, or whatever their edited form is after you see the new homepage layout!

**Comment by amandavisconti** [comment]
Could you cut the FAQ width to half the page, and add a Library section to the FAQ section's right? So we'd have:

FAQ | Library*
Contact us
Events | (Find Us | Open Office Hours)
Student opps
Spatial Tech | Makerspace

**For Library section**
THE LIBRARY'S LAB
We' are the UVA Library's lab for experimental and digital research, teaching, and other forms of scholarship, open to all disciplines and anyone curious about getting their hands dirty.

We're part of the UVA Library's mission to provide equitable access to learning to everyone, and we're proud that librarian superpowers are part of our toolkit! 

Find out about the many ways we collaborate with and depend on our amazing Library colleagues <a href="/library">here, or jump to the <a href="http://lib.virginia.edu">UVA Library's main website</a> to find out more about the whole Library.
