### ISSUE TITLE
Link tags to their section of Posts by Tag page

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#235]
This needs to wait on #659's decisions about tags and categories, and applying tags and categories to all posts.

---

### Context
1. What should the feature do?
- There's a page listing all posts that exist under each tag, with an anchor link on each tag section heading
- When someone clicks on a tag, it should go to that tag's section of the page
2. When and where should the feature appear?
- Wherever tags exist, as the replacement `href` value for the dummy value that exists right now

### Expected Result
- People can see related posts easily without us having to create a filter-able blog/search results page for them to do so
  - The latter can be an eventual goal, but is not plausible for initial release

**Comment by amandavisconti** [comment]
Let's move this to the Rainy Day milestone—isn't critical for release (I think), and we're just brute-force redirecting all old blog posts that have tags/categories in the link to the blog archive page
