### ISSUE TITLE
Add short bios to blog post author credits

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#242]
## Context
- Had this as part of issue #196, where there's a more detailed description
- Author photos are already included now so closed that issue
- Some people have bios, but not everyone, and the branch isn't merged in; so I'm avoiding trying to close that until we have them.
  - Right now to bridge the gap, it just has an auto-generated sentence using the person's name and position title, if it exists.

**Comment by amandavisconti** [comment]
@kbdonnally Is this just for current staff? (The bio blurbs Ronda gathered earlier this year.)
