### ISSUE TITLE
Htaccess redirect implementation

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#247]
http://brettterpstra.com/2013/04/20/wordpress-to-jekyll-handling-redirects/ looks interesting

**Comment by jeremyboggs** [comment]
Currently running the site through [W3C's Link Checker](http://validator.w3.org/checklink) recursively. Will post results here, and we can discuss possible solutions.

**Comment by jeremyboggs** [comment]
So far nothing 404s, but we have a ton of URLs that generate 301 redirects because we don't add a trailing slash at the end. I've created #248 to specifically address this.

**Comment by jeremyboggs** [comment]
We also explicitly ignore a number of status codes—403, 404, and 410—in our [Rakefile](https://github.com/scholarslab/scholarslab.org/blob/master/Rakefile#L42) when we run HTMLProofer on the site. I imagine because we have a bunch of links that do this, and the travis test would fail of we don't ignore these.

**Comment by amandavisconti** [comment]
Known needed redirects:
1. about/charter => charter
2. about/colophon => colophon
3. about/hours-and-spaces => hours-and-spaces
4. about/accessibility => accessibility
5. /archives => blog
6. /geospatial-services => spatial-technologies
7. /research => work
8. /graduate-fellowships => student-opportunities


WP tags, categories?

**Comment by amandavisconti** [comment]
I'm installing the jekyll-redirect-from plugin (which is supported by GitHub Pages) to do the [above](https://github.com/scholarslab/scholarslab.org/issues/247#issuecomment-395069815) redirects.

Info on [setting up a redirect here](https://help.github.com/articles/redirects-on-github-pages/) (basically just add `redirect_from: "/DOGS/"` to the page's front matter)

**Comment by amandavisconti** [comment]
The unchecked redirects [above](https://github.com/scholarslab/scholarslab.org/issues/247#issuecomment-395069815) are going to be the problem with this. I'll just not push the branch I was trying the plugin out in (ghost-link-fixin).

@jeremyboggs or @mossiso, would you be willing to create redirects in an gtaccess file for [the list above](https://github.com/scholarslab/scholarslab.org/issues/247#issuecomment-395069815) plus any other redirects we need?

**Comment by amandavisconti** [comment]
Also links that point explicitly to scholarslab.org

**Comment by amandavisconti** [comment]
Figure out what to put in htaccess to do this

**Comment by amandavisconti** [comment]
Think I can't test this out until we've got the production site off GitHub Pages servers.

**Comment by mossiso** [comment]
Working on that this week. Next week I'm out for conference and Digits meeting, so probably nothing solid until week of Aug 13.

**Comment by amandavisconti** [comment]
@mossiso Do you know the status of this?

**Comment by mossiso** [comment]
I got busy with server migrations and haven't worked on this in September. If I remember a conversation from @jeremyboggs right, for now we are just going to push to the server directly, and figure out the automatic pull from GitHub later.

**Comment by amandavisconti** [comment]
Going to set up the inelegant Jekyll redirect-from plugin for now to deal with this issue

**Comment by amandavisconti** [comment]
- [x] static pages

Links that point explicitly to scholarslab.org

Internal links are using the wordpress formulation for slugs, which includes categories. Our slugs won't have that, so the links are breaking... Unless we'd like to use the existing permalink structure? I think I'd prefer the latter, given how much content this issue affects.

redirect_from: "/about/colophon/" is not available

**Comment by amandavisconti** [comment]
Updated navbar logic to leave out pages _without_ nav = true, instead of _with_ nav = false. This makes it so that the redirect pages generated by jekyll_redirect_from don't get added to the navbar!

**Comment by amandavisconti** [comment]
Committed work to the 247 branch before messing with blog permalink structure. See bookmarks for help retaining archival blog post URL structure (lowest-ID-category/title) but structuring future posts better (YYYY/MM/DD/title?).

Can use defaults scope to separate archival & new posts and treat their URL structure differently? But need to first figure out how Jekyll handles
1. no categories (for archival posts, need to add Uncategorized to post YAML)
2. multiple categories (need to pick the one with the lowest ID number; not sure how Jekyll currently picks—YAML list order, maybe?) May just need to do nested search (if contains ID 1, move that category to top of YAML list; if no ID 1 but ID 2, move that category to top of list, etc.)

**Comment by amandavisconti** [comment]
On hold while Ammon and Jeremy work on post-commit hooks (possibly done by end of this week? 11/16), workflow for our own servers. Then:
- [ ] Set up htaccess to account for all existing jekyll-redirect-from's (plus change colophon redirect to anchor on /about)
- [ ] remove jekyll-redirect-from plugin
- [ ] Set up redirects for blog posts?
- [ ] Update blogging documentation to account for production site being on our own servers

**Comment by amandavisconti** [comment]
Ammon is currently working on htaccess redirects, per Jeremy

**Comment by amandavisconti** [comment]
Known needed redirects:
- [ ] All blog posts
- [ ] /about/colophon => /about/#how-was-this-website-made
- [ ] /about/accessibility => /accessibility
- [ ] /archives => /blog
- [ ] /about/charter => /charter
- [ ] /graduate-fellowships => /for-students
- [ ] /geospatial-services => /spatial-technologies
- [ ] /research => /work

Unknown whether need redirects:
- [ ] Subpages of the redirected pages above?
-[ ] Events

**Comment by amandavisconti** [comment]
I believe @jeremyboggs has implemented our redirects for nginx
