### ISSUE TITLE
Display all of an author's blog posts on their /people page

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#254]
@walshbr would like the individual people pages to list all of a person's posts, rather than just their last 3 posts. (He expected the "all posts" button below the 3 recent posts to bring him to all of that person's posts, not the entire /blog page).

Use case: former Praxis fellow can point prospective employers to their SLab people page, where all their posts are listed

@kbdonnally I can change do this if you think changing from 3 most recent => all an author's post works well. If not, we can mark this as a task for post-public release.

**Comment by walshbr** [comment]
Thanks for making this! To clarify what I was thinking - I think the current page works and looks great. Would just expect the all posts button to either expand the list to include all of them or to point to separate page listing all the posts for that one person. But open to other ideas.
