### ISSUE TITLE
Decide on where blog post media should be stored

### ISSUE THREAD

**Issue by rondauva** [scholarslab/scholarslab.org#258]
### Context
1. What should the feature do?

Technical documentation explaining how users should upload media files for inclusion in blog posts. (images, video, audio)

2. When and where should the feature appear?

Site documentation

### Process
1. Potential Impact on Code or Other Features
2. Suggested Implementation

### Expected Result
Documentation file with clear, step-by-step instructions, teachable in 20 minutes.

**Comment by mossiso** [comment]
Yep, definitely. 
A question for clarification: Are we not wanting to have media files in the GitHub repo? 

Some initial thoughts...

If media files are in the GitHub repo: 
- pro: no separate process for media files when creating a post
- cons: large files in the GitHub repo

This decision may depend on the deployment workflow.

**Comment by amandavisconti** [comment]
I'm concerned about the cost of storing large files (particularly video/podcasts?) on GitHub.com, but I'm not sure what a workflow for doing otherwise would look like?

I don't think we often want versioning of files in the media directory, or to include those every time we rebuild or download the repo somewhere, but I assume there are ways to mark the media directory so that doesn't happen?

Thanks!

**Comment by amandavisconti** [comment]
#360 (documentation for how to author/edit pages/posts) will wait for the decision on this

**Comment by amandavisconti** [comment]
@jeremyboggs @mossiso  @shane-et-al I'm going to write the documentation, for now at least, to have folks upload any media via GitHub.com. Am I right in assuming someone is setting up a nightly build, and that build will pull in all updates to the master branch? (If not, we should reopen this issue.)

**Comment by amandavisconti** [comment]
I declare we're putting media... somewhere on this GitHub repo (I'll decide exactly where & folder structure when I write the documentation next week). Will create a Rainy Day ticket to see if this e.g. makes cloning the repo take too long, or if Jeremy's method of migrating stuff to static.scholarslab.org could be automated to happen every quarter.
