### ISSUE TITLE
Update 3rd para on Praxis page to include last two years' projects

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#260]
http://maybe.scholarslab.org/praxis-program-fellowships/

In the third paragraph, the projects listed only go up through the Clockwork team. NOT a rush, but could you add a sentence for each of the last two year's teams there?

**Comment by walshbr** [comment]
I have this up on a branch. Also fixed some relative links on the main pedagogy page. But did you want this to be merged into master or into your content to end all content branch @amandavisconti

**Comment by amandavisconti** [comment]
Excellent! master would be good
