### ISSUE TITLE
Move search field into navbar?

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#262]
Instead of a link to a /search page, would it be possible to have a field to search the site visible in the top navbar?

**Comment by ZoeLeBlanc** [comment]
Definitely possible and I'm happy to help but should be driven by @kbdonnally 's design vision. The way I did it for Jefferson Notes was create a search bar that then shows a div with all the results, rather than redirecting the page. Let me know what you're thinking and I can try and help 😄
