### ISSUE TITLE
Code blocks not parsing

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#27]
https://scholarslab.github.io/scholarslab.org/visualization%20and%20data%20mining/working-with-d3-part-2/

**Comment by jeremyboggs** [comment]
One hurdle for this is accounting for the different ways we've included code blocks in our posts. Pretty sure it's at least a half-dozen different ways.

**Comment by jeremyboggs** [comment]
Looks like this has been resolved, at least on [Ammon's blog post about D3](http://maybe.scholarslab.org/2016/01/19/working-with-d3-part-2/) that @walshbr originally referenced. Some other formatting issues on that page, though, but not the code blocks.

We might make the code render in a more appealing way, but I think that's a low priority given other issues.
