### ISSUE TITLE
Names of Summer 2018 LAMI Fellows for /people

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#272]
Either create /people pages for them, or send me a list of their names and I am happy to

**Comment by walshbr** [comment]
Got stub pages up on a branch. Waiting on photos from Shane and (more of an actual delay) the LAMI students to send me bios to stick in there. Then I will finalize. Will probably be next week sometime, given how long it usually takes to track down all of the data.

**Comment by walshbr** [comment]
All of the bios are up on the SLab production site and in this repo. Just need photos from @shane-et-al  and then we can go ahead and make the stuff live. The wordpress thing will need to have a line of the theme tweaked to get the current students show up.

**Comment by amandavisconti** [comment]
I merged this so we'd have the content on the site, but I need to fix the YAML so they appear under "current" and have "LAMI Fellow" as role.

Will leave this open so @walshbr  can add photos once he has them.

**Comment by walshbr** [comment]
Almost got em all

**Comment by walshbr** [comment]
Should be good now.
