### ISSUE TITLE
Make all section titles on homepage into links

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#276]
People usually expect to be able to click on section titles, so while they shouldn't be _styled_ as links, they should be clickable if someone tries.

This isn't that important on desktop, but is very important on mobile.

**Comment by kbdonnally** [comment]
@amandavisconti also assigning you to this because I wanna ensure the homepage sections are finalized before implementing this change

**Comment by amandavisconti** [comment]
Just need to add a Library section as described in #230, then we'll have the following sections below hero text, which can have their titles linked:

FAQ | The Library's Lab
Contact us
Events | (Find Us | Open Office Hours)
Student opps
Spatial Tech | Makerspace

Thank you!
