### ISSUE TITLE
Homepage contact section: change "below" to "to the right" on large screens

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#277]
### Situation:
Right now, there's a newsletter sign-up form in the contact section. It shows up below the content on mobile screens, but on large screens it shows up with the text on the left and the sign-up on the right.

### Solution:
Two `span` elems: one w/ "below" and one "to the right". Display only the appropriate `span` at a given screen width using media queries.

**Comment by jeremyboggs** [comment]
@amandavisconti We should probably research some alternative ways of describing relevant adjacent content, that avoid directional words.

**Comment by amandavisconti** [comment]
Directional text not on homepage,not needed, impending redesign will cover
