### ISSUE TITLE
Update PR template to prompt specifically typing "closes #X"

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#278]
### Situation
PR template asks about related tickets, but it's easy to forget to type "closes #xyz" if the PR fixes the ticket in question.

### Solution
Update PR template to also prompt people to specifically prefix any issues that are fixed by that PR using the keyword of their choice ("closes", "fixes", there are probably a couple more...).

**Comment by amandavisconti** [comment]
I fixed this, will merge in a moment
