### ISSUE TITLE
Find an replace any of your weird em dashes

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#284]
Replace command-shift-hyphen with &mdash;

**Comment by kbdonnally** [comment]
Your em dashes are not weird!!! utf-8 encoding is :)

(Also I don't know if you meant this already, but please use the literal `&mdash;` string when replacing! <3 you rock)

**Comment by amandavisconti** [comment]
Forgot to codefence that, I will not in fact replace my —s with more —s
