### ISSUE TITLE
Fix background styles on pages darker than new navbar background

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#287]
### Context
Background colors on some dark-themed pages currently look weird b/c they're pure black and the new navbar is 13% lightness gray. Need to resolve the styling issue.

### Associated Product Ticket
- Issue created from PR #286 
### Process
- Probably just change those colors to the dark gray used in nav, but will explore effect on individual pages once get to it.

### Expected Result
- Cohesive color palette and nice flow.

**Comment by amandavisconti** [comment]
May be addressed by retheme; closing this ticket and referencing in https://github.com/scholarslab/scholarslab.org/issues/1001 (lists old theme issues that could be addressed/mooted by retheme; with note to reopen those issues if they are still problems at that point)
