### ISSUE TITLE
Twitter feed

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#29]
Somewhere, perhaps after [MITH's style](https://mith.umd.edu)

<img width="449" alt="screen shot 2018-04-04 at 8 22 06 am" src="https://user-images.githubusercontent.com/48310/38307327-5f08b576-37e1-11e8-96a9-186e26712464.png">

**Comment by amandavisconti** [comment]
Working on this

**Comment by walshbr** [comment]
I saw this but hadn't played with it yet - https://github.com/rob-murray/jekyll-twitter-plugin. Looks like you might have to play with the CSS a lot depending on what we want out of it.

**Comment by amandavisconti** [comment]
Twitter embed makes grabbing just the text of the tweet difficult—will need to use JS if we want to style/unstyle embedded latest tweet.

**Comment by nabsiddiqui** [comment]
I'm not sure if this still works when you render the site static, but it should. 

Currently, the Twitter embed allows you to manipulate the style of the tweet using CSS.  If you embed the tweet, it should show up as a blockquote with a "twitter-tweet" class.  The plugin itself shows up in a div with the class "jekyll-twitter-plugin."  You should be able to manipulate that through your stylesheets and you can pass parameters to the jekyll twitter plugin.  

More info: https://dev.twitter.com/web/overview/css

Hope this helps.

**Comment by amandavisconti** [comment]
Possibly separate task: pull photos from Will's Twitter feed (or just photos from tweets SLab handle tweets or MTs/RTs?)
