### ISSUE TITLE
Review/correction of last post import

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#299]
Catch any content (events, posts) and get these represented on the new website. Brandon migrated the event archive but not the (6?) draft events, so check if those have been published or if we want to save the drafts elsewhere
- [ ] Events
- [ ] Posts

**Comment by walshbr** [comment]
I'll take a look at this

**Comment by amandavisconti** [comment]
Jeremy migrated posts over 11/20/2018 2:30pm EST, Amanda is now reviewing/correcting these posts
