### ISSUE TITLE
Travis Integration

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#31]

**Comment by walshbr** [comment]
Ran travis on a travis branch, and there are a bunch of things to take care of before actually running it will be useful. For one, it's giving an error for any:
images that don't exist - the people images, for the most part.
alt attributes that don't exist for images. Will keep tweaking it to get a usable log.

**Comment by ZoeLeBlanc** [comment]
Think I've gotten travis up and passing now. I'm suppressing alt attributes which we might want to change in the future and I've tweaked the post layout to work when we don't have images of people. Closing this issue.
