### ISSUE TITLE
Complete list of labeled places on 'FIND US' section of homepage

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#311]
## Situation
- Currently displays filler text along with like one actual room
### Related
- Can't complete #197 until know spaces to label

## Solution
- Need desired places as list instead
- Can just use the ones in Hours & Spaces page but would prefer to know a) desired list (@amandavisconti   @lam2c ), not my guess and b) not to type the content myself if possible

**Comment by amandavisconti** [comment]
Alderman 421*
Alderman 423*
Staff offices (same color for main office room; GIS/Pedagogy wing; and Alison, Jeremy, and Amanda's offices)
Makerspace
Common Area
Open Office Hours (just color the presentation space at the front left of the Common Area)

* Could instead use one color for "Classrooms & events: Ald 421 & 423" if works better space-wise

@kbdonnally Let me know if this isn't what you need?

**Comment by kbdonnally** [comment]
@amandavisconti what room is Alison's office?

**Comment by amandavisconti** [comment]
@kbdonnally It's the "think tank", a little glassed-in square room just to the northeast of Ald 423 (you walk between it and some copy machines to enter 423). I can't remember what the room number is...

**Comment by kbdonnally** [comment]
Edited PR message, but not til after merge - this is closed by #323.
