### ISSUE TITLE
Prevent project gallery from scrolling past end of items

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#316]
Right now clicks slightly past end. Not functional issue but just makes it look less professional.

Fix w/ JS, though unsure what the math looks like rn.

**Comment by kbdonnally** [comment]
Maybe just use anchor link & a button that scrolls to it, so that there aren't any awkward issues w/ trying to get it aligned during the demo?

**Comment by walshbr** [comment]
@amandavisconti - I think we can close this since you redid how the projects are displayed. There is no scrolling to speak of, and things are just presented in a grid.
