### ISSUE TITLE
Change layout on research project detail pages to show nav

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#317]
## Situation:
- Currently doesn't show header w/ it b/c was trying to design as a lightbox thing
- Either implement as lightbox or just make them normal pages
  - If make them normal pages need to figure out a way to keep gallery from resetting to 1st item, so I'm inclined towards lightbox
### Related:
- #136 (closed but relevant), #201 (only other open issue to do w/ these pages)

## Solution:
- Try to do lightbox w/ CSS `:target` pseudo-class & IDs for each
  - Relevant [Mozilla page](https://developer.mozilla.org/en-US/docs/Web/CSS/:target)
- If lightbox, include link to full page, so will need to update that layout to `default` either way
- If pure CSS doesn't work, use JS to populate

**Comment by amandavisconti** [comment]
@kbdonnally  How about we just implement these as normal pages for now (until we get the rest of the public launch tasks done), and we could return to the lightbox idea after?

**Comment by amandavisconti** [comment]
Fixed on finalize-projects-page branch by switching to layout: default, but still needs vertical padding & check multiple project pages to insure correct

**Comment by amandavisconti** [comment]
Closed, moved to #454
