### ISSUE TITLE
Controlled Vocabulary for Project Metadata

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#32]
@rondauva had the good point that we should have controlled vocabularies for the metadata that are looser. 
The collaborator's role category would be one. We can autogenerate the list of potential fields in the rake
task for new_project.

**Comment by amandavisconti** [comment]
Changing to: look through the /_work YAML and make sure it's full

**Comment by amandavisconti** [comment]
Combined into #376
