### ISSUE TITLE
Implement Gulp to test its ability to keep codebase organized & prefix CSS

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#320]
## Situation:
- Manually prefixing CSS is prone to error, but we need CSS consistently prefixed
- JS is hard to keep track of when all in a giant file, & Gulp concatenates it while removing whitespace
### Related:
- #64, #193 

## Solution:
- Try setting up [Gulp 4](https://github.com/gulpjs/gulp/blob/master/docs/API.md) and see how it works
- Make a snapshot tag before implementing any of this, so that if it is Not Great, we can easily go back to old system
- Will keep detailed docs of setup so we know exactly why we did what
  - There's also some Gulp setup commits & stuff in my (@kbdonnally) patterns repo, which I'll probably be drawing from

**Comment by kbdonnally** [comment]
Did have it as Rainy Day, but moved to Public Release because the JS file is getting too long to easily edit now so I'mma try this a$ap rocky

**Comment by amandavisconti** [comment]
Closing; there's a separate Moar SASS issue
