### ISSUE TITLE
Add JS to highlight name of a space when hover/tap on SVG shape

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#325]
## Situation
- Have interactive 'Find Us' hours-and-spaces section SVG mostly implemented, but only works one way in terms of coordinated highlighting b/t name of a space and the SVG drawn over the floorplan of that space
- Want it to work both ways, esp since hovering over the spaces does highlight them rn

## Solution
- When have reasonable time, implement JS event listeners that do similar action to the ones you already have, but the opposite direction
- Probably refactor the JS while you're at it, since there's some redundant code in there right now (since you assumed you'd be able to get to this sooner, some of the variables are already set up)

### Related
- #324, #197

**Comment by amandavisconti** [comment]
Closing since we're moving out of this space in May
