### ISSUE TITLE
RSS feed for site

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#330]
Related to #18 
- [x] https://twitter.com/jglovier/status/414142797713661952
- [ ] Set up blog RSS feed to post to SLab Slack channel (https://get.slack.help/hc/en-us/articles/218688467-Add-RSS-feeds-to-Slack)

**Comment by walshbr** [comment]
I tweaked one thing to the feed.xml template, and we're validating now - https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fmaybe.scholarslab.org%2Ffeed.xml.

**Comment by amandavisconti** [comment]
Moved #1 to #407 as I want to wait for the non-dev URL before setting up
