### ISSUE TITLE
Links to our campus and external collaborators and funders

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#335]

**Comment by jeremyboggs** [comment]
This needs some details/scope, including:

1. A starting list of these links;
2. Suggestions where we might wish to display this list.

**Comment by amandavisconti** [comment]
1. Pass through existing projects to add any faculty collaborator(s) to YAML
2. Ditto for any internal or internal grant funding
3. Set up project spreadsheet to have clear columns for listing all of a project's collaborators and funders

I don't think we have a good place to e.g. put funder logos
