### ISSUE TITLE
Staff bios link out

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#340]
Staff bios link to web presences, publications, projects (SLab and external)

**Comment by jeremyboggs** [comment]
We already seem to do this.

**Comment by amandavisconti** [comment]
@jeremyboggs Idea was to add to existing social links with links to projects from outside SLab (e.g. dissertation), papers and other writing (e.g. Will's CLIR chapter). But I'd be up for closing some of these small idea-type issues—this one feels like if it's important, we'll remember and make time for it.
