### ISSUE TITLE
Change top-level nav "pedagogy" to "For Students"

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#344]
@walshbr Your final call on this!

Some folks think this isn't clear about what's offered. Not sure if we'll find an accessible way to switch to nested menus (which I think would help), but are there other words that would help folks interested in:
- fellowships/internships general info
- calls for applications for fellowships/internships
- ditto for makerspace technicians
- info on how we study & practice pedagogy
- faculty who'd be interested in knowing how we can help their students (I worry faculty on the site for non-student reasons would ignore a page labelled just "students", but I may be wrong)
immediately realize that's the page they should go to? "Student opportunities" was floated, but something shorter would be nice.

**Comment by walshbr** [comment]
Lets go with "For Students" @amandavisconti. The faculty scenario is a good idea, but I think it's an edge case for the audience that we're actually trying to reach. I.e. - a faculty looking for opportunities for students would be likely to look at a page called students, which is a better thing to plan for than for other faculty finding the page by accident and then retroactively finding it useful for their students. Pedagogy and/or Opportunities can be nested pages within a "For Students page" if we can't get them to nest in the menu. I don't think there is a concise way to describe everything, and "For Students" gets a nice little link to the pedagogy we'll talk about, which is that we're here for them.
