### ISSUE TITLE
Fill out our project spreadsheet (which can be used to add projects to the site)

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#345]
On our project spreadsheet (see Slack channel for link), help fill in the columns. Stuff that isn't needed to update the website is highlighted in gray, so just fill out the white columns.

Issue #430 will move these to the site so they appear on our /work page.

**Comment by walshbr** [comment]
Mentioned this on #375, but the student project information is all in a data file so could very much just be pulled in and deployed wherever you want.

**Comment by amandavisconti** [comment]
Brandon has finished adding student projects to the spreadsheet. See #375 too (you may be able to try out the idea to pull student projects as data files into the pedagogy page, concurrent with adding other projects from the spreadsheet to "Our Work"

**Comment by amandavisconti** [comment]
Combined into #376
