### ISSUE TITLE
Switch to nested navbar, using updated site info architecture

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#356]
For main navbar: nest items and show 4-5 top-priority links at regular laptop browser window size

Brandon says: IIRC, the nav bar currently displays just about all the main pages, but the intention was to eventually select from among the current options to have a more curated list. If that's the case [Amanda: yes!], we should decide what top-level links we want to appear there to get a more reasonable listing.

**Preferred menu structure is:**

1. about
-people
-hours & spaces
-charter
2. blog
3. our work
-spatial tech
-makerspace
-UVA Library
4. events
5. for students
-maybe list 5 or fewer or the student subpages here? (@walshbr what do you think?)
-student programs charter

- [ ] I'm a little worried that drop-downs mean folks won't click on the header item (About, Our Work). Is it reasonable to duplicate these in the dropdowns (have an About subitem called "FAQ" that links to /about, and/or a sub-item to Our Work called... I don't know?)

- [ ] I'm not sure where we should put:
accessibility
search
site map
Do these need to go in the main nav? If so, where?

Please feel free to address any/all of these as sounds best to you, if you have time to work on this! Thanks.

**Comment by kbdonnally** [comment]
Good rundown on the ergonomics of modern menu design: http://www.uxbooth.com/articles/the-rules-for-modern-navigation/

**Comment by amandavisconti** [comment]
If anyone is up for working on this & testing it on mobile phones/different screen sizes

**Comment by amandavisconti** [comment]
KD suggested nested navs are rough on accessibility. Look into other ways of clustering topnav items (current nav showing what fits by priority is awesome, but also interested in chunking info to make clearer what goes together?)

**Comment by jeremyboggs** [comment]
@amandavisconti I think if we'd prefer the menu to work like a clickable dropdown, representing some sort of hierarchy, we should do away with the flexible list that changes what's displayed based on the width of the screen in favor of a different mobile-friendly layout.

If the menu structure is what this group prefers, I can put some time into a pull request that implements it.

**Comment by amandavisconti** [comment]
@jeremyboggs I'm fine with whatever! And I'm fine with the current menu for the site release.

**Comment by amandavisconti** [comment]
Will mock this up on 5/30

**Comment by amandavisconti** [comment]
This has too much old/unrelated info in it, so closing and switching to new task #999
