### ISSUE TITLE
Style newsletter confirmation text

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#359]
<img width="1191" alt="screen shot 2018-07-19 at 2 55 27 pm" src="https://user-images.githubusercontent.com/899033/42963999-d2ef1a7c-8b63-11e8-8a0f-a1ef39b317f0.png">

**Comment by jeremyboggs** [comment]
😲

**Comment by amandavisconti** [comment]
Closing. Newsletter link currently takes you to a Mailchimp form, so this no longer happens on the site
