### ISSUE TITLE
Workflow for drafting blog posts

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#36]
Since we'll have people writing on this, we want a way for them to be able to draft things that won't be actually posted live.

**Comment by walshbr** [comment]
Think the Travis Integration can handle some of this - it integrates with Slack, and we can set up HTML proofing for links. It should catch any errors that break the site before they go live, and IIRC you can also enforce some metadata rules with it.

**Comment by amandavisconti** [comment]
This needs to either be teachable in an hour, or be something where folks can draft posts however they want and then give to someone comfortable with posting for them.

**Comment by amandavisconti** [comment]
@rondauva We decided to not use categories nor tags on blog posts on the new site for now; when you write documentation for how to blog, could you ask folks to _not_ fill out tags/categories in the front matter? Thank you!

**Comment by rondauva** [comment]
Outline for this documentation:

documentation needed:
 markdown basics
 
 post structure
 	metadata/yaml
		author: firstname-lastname
		date: YYYY-MM-DD HH:MM:SS+0:00
		layout: post
		slug: title-words-go-here
		title: 'title'
		categories: [always blank]
	headings
	embedded images
		formatting of link
		location to upload image
			associated documentation: how to upload media files to the server and where to upload ([#258](https://github.com/scholarslab/scholarslab.org/issues/258))

**Comment by amandavisconti** [comment]
I'll incorporate @rondauva's work as I document how to create/edit posts+pages using the GH interface for #360

**Comment by amandavisconti** [comment]
Amanda will finish documenting editing/adding posts+pages, then meet with Ronda and Laura to combine with Ronda's text and refine documentation.
