### ISSUE TITLE
Documentation on GitHub.com writing/editing posts/pages

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#360]
The actual documentation to contain writing is stored [here](https://github.com/scholarslab/scholarslab.org/blob/documentation/docs/authoring-and-editing.md)
- [x] remove henry blog post
- [x] remove henry branch
- [x] Check that all internal links (e.g. #cheatsheet) work correctly
- [x] Draft on GH and look at via Netlify

**Comment by walshbr** [comment]
I'll work on this a bit. Will push everything to your same branch as I go.

**Comment by walshbr** [comment]
Remaining to do:
- [ ] Branching
- [ ] Moving work from branch to master
- [ ] Terminology cheatsheet
- [ ] Deploying work
- [ ] Adding new pages
- [X] Markdown

**Comment by amandavisconti** [comment]
@walshbr Thank you!

**Comment by amandavisconti** [comment]
- [ ] Non-git instructions (just using web interface to author/edit)

**Comment by amandavisconti** [comment]
@walshbr I split this into two issues (and two documentation pages)—one for editing/authoring through the GitHub.com interface only (for folks new to this), and one for editing/authoring through git/command line/local Jekyll server.

**Comment by amandavisconti** [comment]
Back working on this today!

**Comment by amandavisconti** [comment]
Reopening this until I resolve merge conflicts https://github.com/scholarslab/scholarslab.org/pull/513
