### ISSUE TITLE
Student Projects Catalog

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#375]
When putting together the list of student projects for development it became really clear that most of our students haven't maintained persistent web presences for their projects. That's fine and understandable in some cases, but it means that the projects' only real record are as abstract ideas on our blog. I'd like to get a catalog of student projects going on here, with no more detail than what I have going on http://praxis.scholarslab.org/projects/. Basically just a blurb, though it might be ideal to link to the blog posts for a particular project as a way of connecting them together as part of an identity. That archive would be useful for me working with the provost's office as well, and it would be a good way to elevate some makerspace student work as well. This would entail two things to the architecture as I see it:

_data/student_projects.yml - a list of entries containing student projects
_include/student_project.html - a template include for the project

It would also entail me putting together a number of blurbs for student projects.

@amandavisconti and I were going back and forth about whether to include this on the Pedagogy or Our Work pages - I could see good reasons for each and will think more. I can put this together on a PR.

**Comment by walshbr** [comment]
@amandavisconti I have this up and working on the "student-project-archive" branch. At the moment it is just a running list at the bottom of the "pedagogy" page. The student project information is all in contained in _data/student-projects.yml. The data there gets pulled into the pedagogy page through an include - would be easy to modify the include for use elsewhere if you wanted it on "Our Work" or if you wanted a different format for it. We could merge this whenever. On the one hand am inclined to hold off since there are more pressing issues to worry about, but am happy to defer to you.

**Comment by amandavisconti** [comment]
@walshbr Awesome, thank you! I'll make a note to myself to see if I can merge this.

**Comment by amandavisconti** [comment]
@walshbr I think this is just waiting to be merged, but let me know if this is no longer what you want for the for-students page? I can do it, just wanted to check first.

Also possible before merge:
- [ ] UVA Reveal shows "Related posts" with nothing under it
- [ ] Turn student names into links to their bio pages
- [ ] Bold "types:", "dates:", etc. to make visual skim easier

**Comment by walshbr** [comment]
Yah I'll take a look in the coming weeks. Those are good catches! And since this was made so long ago I want to double check it to make sure that it still works as intended.
