### ISSUE TITLE
Move off KD's Typeface account before launch

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#384]
Currently using KD's Adobe Typekit account, need to disconnect and find other font solution

**Comment by jeremyboggs** [comment]
What are we using Typekit for?

**Comment by amandavisconti** [comment]
@jeremyboggs I'm not sure; I'll DM Katherine.

**Comment by jeremyboggs** [comment]
sorry, i just looked at the source; we're using it for the monospace font in the citation and eyebrow, among other places. IF we can just use this same font on a free typekit plan, we can make a scholarslab one. Otherwise, I think we need to find a replacement font.

**Comment by amandavisconti** [comment]
@jeremyboggs KD says:
Anything labeled “base-mono-narrow” or “base-mono-wide” is TypeKit
The rest is Google

**Comment by jeremyboggs** [comment]
nope, can't use it on a free plan. Will look for a replacement.

**Comment by walshbr** [comment]
@jeremyboggs did the changes to the font that you made resolve this?
