### ISSUE TITLE
Improve/reduce blog post categories & tags

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#39]
I think we need to keep the first listed category for any blog post when we migrate them, because slab.org/category-name/post-title is the old URL structure. Beyond that, let's  
1. discuss what categories/tags are useful for on the new site (if anything), and  
2. document what possible tags/categories people can include on new posts (in #38)

Need to look [at this page](http://maybe.scholarslab.org/posts-by-tag/) and maybe remove single-post tags

**Comment by walshbr** [comment]
Am I right in thinking that we want the old posts to maintain the same permalinks even if we get rid of post categories? Otherwise we would break links to our pages from the outside.

**Comment by jeremyboggs** [comment]
> Am I right in thinking that we want the old posts to maintain the same permalinks even if we get rid of post categories? Otherwise we would break links to our pages from the outside.

Yeah, or set up reliable 301 redirects.

**Comment by amandavisconti** [comment]
**1. how to retain or redirect links that rely on these (e.g. many post URLs contain a category name).** 
@jeremyboggs: can you brute force redirect all of those old posts to the new scholarslab.org/blog URL (or assign to someone?)

**2. What categories or tags, if any, we want going forward (how would we use these)**
Not critical for public release. #270 puts this work in Rainy Day milestone, and #235 relates to tags but is on the Rainy Day milestone also

**Comment by jeremyboggs** [comment]
Closed, with the intent to address issues discussed here in #26.
