### ISSUE TITLE
Style blog pagination

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#394]
Following up on #293 

Blog pagination needs styling:
- [ ] Navbar says "Blog | 74" (Asked @jeremyboggs if this is the count of total pages. How should we style this so it makes sense to readers? I'd just remove it from the navbar...)
- [ ] Style "older"/"newer" links
- [ ] Either move "older"/"newer" links to bottom of post page, or duplicate and place at both top & bottom of page

**Comment by walshbr** [comment]
I just opened a pull request for the first checkbox - #398. Take a look and merge? If you click the dropdown, it looked locally for me as though it was actually shoving every paginated blog archive page into the nav. @kbdonnally already had things set up really well, so was an easy fix thanks to her work 🎉 

That won't address points two and three though.

**Comment by walshbr** [comment]
@amandavisconti correct me if I'm wrong, but I think we still need to do:

- [ ] Style "older"/"newer" links
- [ ]  Either move "older"/"newer" links to bottom of post page, or duplicate and place at both top & bottom of page

**Comment by amandavisconti** [comment]
@walshbr Thank you for catching that!

**Comment by jeremyboggs** [comment]
Fixed in 30f838873448f3e8406542f07d1a803298fa1730.
