### ISSUE TITLE
Nix blue box when bio has no "around the web" links

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#399]
When a bio has no "around the web" links, there's just an empty confusing box left on the page (see screenshot below, example from Nora's bio page)
![screen shot 2018-08-10 at 2 59 58 pm](https://user-images.githubusercontent.com/899033/43976314-2daab268-9cae-11e8-86cd-d338730f119d.png)

**Comment by walshbr** [comment]
@amandavisconti pushed up  #402 for this -  it def works for all people pages that have 'None' as values for those categories. If someone creates a person page with the rake task that should be fine. But I  couldn't get the logic to check to for nil values as well, as boolean stuff in Jekyll always vexes me. I checked all our people pages, and this fix catches all of them. If we have edge cases in the future I suppose ew can address them.
