### ISSUE TITLE
Document Publishing Workflow

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#4]
Add documentation in README for how folks can contribute to the site.

**Comment by amandavisconti** [comment]
Social media workflow => IFTTT-style post to Twitter within specific time range? (8am-12pm EST)
Scoop Tramebot
Ping people when new post added (in case needs formatting improvement/etc.)

**Comment by walshbr** [comment]
Duplicate of #64 #90
