### ISSUE TITLE
Link RSS feed to our Slack

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#407]
Set up blog RSS feed to post to SLab Slack channel (https://get.slack.help/hc/en-us/articles/218688467-Add-RSS-feeds-to-Slack) so we see our latest posts

**Comment by jeremyboggs** [comment]
@amandavisconti Closing this. I'd recommend you (or someone) go ahead and do this with our current feed (at http://scholarslab.org/feed/) and we'll keep this URL by addressing #529.
