### ISSUE TITLE
Events Page Missing Text

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#415]
Current stub text in _layouts/events.html

"Questions?
Contact Ronda Grizzle (rag9b@virginia.edu), HostName Two (email@virginia.edu), or HostName3 Lastnamez (emailz@virginia.edu)."

Should we just leave this at contact ronda?

**Comment by walshbr** [comment]
Actually, the lorem ipsum in there is worth looking at in general. It also has some stuff about required skills that probably aren't universal.

**Comment by amandavisconti** [comment]
Working on this

**Comment by amandavisconti** [comment]
Changed email address to Laura, removed code that pointed questions to author of events post
#429 has info updating YAML to pull in text on event requirements & audience
Also removed some files' YAML that were KD's notes e.g. on time needed to finish file work

**Comment by walshbr** [comment]
Reopening this because it looks like the "contact Laura" bit has gotten squished out of existence somehow. I'll try to investigate later. Looks like this even though the text is in the md file:

<img width="969" alt="screen shot 2018-08-17 at 8 44 42 am" src="https://user-images.githubusercontent.com/2334220/44266793-e377ad80-a1f9-11e8-8768-be965a90a8c3.png">

**Comment by walshbr** [comment]
Oh wait that might have been a caching thing. It looks good now!

**Comment by amandavisconti** [comment]
Best kind of reopening/closing!
