### ISSUE TITLE
Project page "when" info should show e.g. "2013" instead of "2013-2013"

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#435]
Current work.html layout uses `When:</span><div>{{ page.start-year }}-{{ page.end-year }}`. Want to add a check so if start-year is the same as end-year, just start-year is displayed. (E.g. if it says 2013-2013, it should just say 2013 instead)

**Comment by walshbr** [comment]
@amandavisconti - what is an example page for this? And is this _layouts/work.html? For some reason I'm having a hard time seeing this and finding the related code block.

**Comment by walshbr** [comment]
K i'll take a look!

**Comment by amandavisconti** [comment]
Opened #443 to address that, closing this. Thanks @walshbr!
