### ISSUE TITLE
Blog posts not showing up live

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#438]
They show up in the archive locally but not on http://maybe.scholarslab.org/blog/

Likely a dependency compatibility thing with GitHub

**Comment by walshbr** [comment]
Ah this is the problem - https://github.com/jekyll/jekyll/issues/6702. We're using a newer version of the gem not supported by github pages. That won't be an issue if we move off github but it's not working under the current setup.

**Comment by jeremyboggs** [comment]
Fixed the glitch in 30f838873448f3e8406542f07d1a803298fa1730.
