### ISSUE TITLE
"Scholars' Lab in the News", DH Now, & DH Lib citation list

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#439]
I.e. link to when SLab is in the news
Blog post, or special section of front page?

Use:
- [ ] SLab in the news (existing GDoc)
- [ ] SLab DH Now citations (existing GDoc)
- [ ] SLab DH_Lib citations (existing GDoc)
- [ ] Will's CLIR whitepaper
- [ ] Ask staff for other blog websites, posts, documents/reports to link to
- [ ] http://literaturegeek.com/tag/dh-now/
- [ ] http://walshbr.com/categories/dh-now/

**Comment by jeremyboggs** [comment]
This could be a separate data file, that we parse to display most recent mentions?

**Comment by amandavisconti** [comment]
@jeremyboggs This is more a page listing all the times we've been in the news (from the list Laura created). But yeah, I actually had this working from a data file, I think last fall? It worked nicely for keeping the news to short info-loaded sentences. Am mostly waiting to implement until I feel like I'd keep up with updating it...
