### ISSUE TITLE
Footer contact info

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#48]
- [x] physical address (note the address in our footer is incorrect. It should be P.O. Box 400109)
- [x] CC license
X sign up for email announcements (NOPE: this is now in homepage body content)
- [x] our email
- [x] our phone
X our fax?? (NOPE: let folks email us if they need it, not listing in footer)
- [x] slab logo
- [x] uva library logo
- [x] twitter
- [x] facebook
- [x] github

**Comment by jeremyboggs** [comment]
@rondauva @lam2c We need to determine what Mailchimp (which is what we use for newsletter registration) will accept on a form submit. Can one of you do this? 

If it won't let us gather those things, then we need to discuss whether this feature is important enough to explore other code and/or newsletter options.
