### ISSUE TITLE
Search Feature Linking Bug

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#481]
I think we've changed our URL construction from when the search feature was implemented, so the URLs don't resolve. An example - http://maybe.scholarslab.org/Announcements/Digital%20Humanities/day-of-digital-humanities-2009. 

I'll check the thing to see how it is generating those.

**Comment by walshbr** [comment]
Actually going to assign @ZoeLeBlanc since, looking at the search code, it's not immediately clear to me how the URLs are constructed. Looks like, for what it's worth, the URLs used to be 

baseurl / categories / slug

now they are 

baseurl / date / slug

**Comment by walshbr** [comment]
I think @amandavisconti would know best

**Comment by amandavisconti** [comment]
@ZoeLeBlanc Thank you! We're hoping to have SLab staff and Dennis' approval near the end of this month (10/29). Would that be feasible?

I'm not sure how easy this is to fix, or whether it's impacting all searches on the site.
