### ISSUE TITLE
Fix weird homepage photo tiling

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#489]
![screen shot 2018-10-05 at 7 49 39 am](https://user-images.githubusercontent.com/899033/46533616-40dfc080-c873-11e8-802d-870da57eb773.png)

**Comment by walshbr** [comment]
Just merged a PR to fix this @amandavisconti. I think the sizing on that image could be optimized a little now though, since the tiling was what allowed it to fill the space given to it when the dimensions of the photo didn't work for that space. I'll make a rainy day issue to look at that.
