### ISSUE TITLE
Sizing of For Students Image on Front Page

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#492]
The image used to tile, which allowed it fill space as the screen window shrank. We took off the tiling because it looked wonky, but now that means that the dimensions of the box don't quite work at smaller screen sizes. We should look at either cropping the photo to minimize this or revisiting the CSS to make it fit better.

**Comment by jeremyboggs** [comment]
@walshbr How did you take away the tiling? What were the commits that remove it?

**Comment by walshbr** [comment]
I believe it was a background image tiling before rather than a straight-up img tag. Lemme find the commit.
