### ISSUE TITLE
Theme-testing folder

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#498]
Related to #485. It looks like the theme-testing folder has a lot of notes, screenshots, etc. KD used while making the site. Probably would be good to archive these somewhere in case we/she wants them and get them out of the repo, just because the folder is ~150 MB right now.

**Comment by amandavisconti** [comment]
@kbdonnally Wanted to make sure you saw—I moved your folders theme-testing, logo-testing, and _todo to a separate repo (so they're not bulking the active site repo): https://github.com/scholarslab/future-slab.org
