### ISSUE TITLE
Deal with dependency warning

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#500]
Can we update this without breaking anything? Looks like we just need to change from Jekyll 3.8.3 to 3.8.4 in the Gemfile and test stuff locally:
![screen shot 2018-10-07 at 7 57 42 am](https://user-images.githubusercontent.com/899033/46581432-b62fca80-ca06-11e8-9cfc-c33b4d8e5b41.png)

**Comment by jeremyboggs** [comment]
Fixed in 017bc16.
