### ISSUE TITLE
Margins above headers should be more

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#524]
On some pages, particularly on mobile views, headings seem a bit too close to the preceding paragraphs, making it difficult to distinguish these sections. A simple solution would be to increase the margin-top on these headings.

**Comment by amandavisconti** [comment]
May be addressed by retheme; closing this ticket and referencing in https://github.com/scholarslab/scholarslab.org/issues/1001 (lists old theme issues that could be addressed/mooted by retheme; with note to reopen those issues if they are still problems at that point)
