### ISSUE TITLE
Optional pronouns on bio pages

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#532]
Could look at other things to add to bio pages at same time. E.g. UVA Library UX's redesign of staff directory pages includes optional pronouns but also stuff like languages you speak/read/write, stuff you're the right person to ask about...

**Comment by jeremyboggs** [comment]
> Could look at other things to add to bio pages at same time. E.g. UVA Library UX's redesign of staff directory pages includes optional pronouns but also stuff like languages you speak/read/write, stuff you're the right person to ask about...

Agreed, but suggest we group those under a "project" or a "label" and consider fixing/closign this partiuclar ticket about pronouns. Otherwise, this ticket will be perpetually open. 😸
