### ISSUE TITLE
Consider using Jekyll to build search assets

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/scholarslab.org#539]
Currently, we use a rake task to walk over most of the files in our project and build a `corpus.json` file. Then, we have a second task to read _that_ json file to build an `search_index.json` file. This process could benefit from using Jekyll itself to build these files; Namely:

1. It would add everything Jekyll uses to build the site in the corpus, instead of explicitly having to tell the rake task which files to skip and which to include;
2. It would help us correctly parse the page/post content, which would resolve #521;
3. It would automagically include any new or edited content while running locally—as it stands, you have to re-run `rake` to include new or edited content for it to be included in the corpus and index.

**Comment by amandavisconti** [comment]
Currently displaying metadata oddly (e.g. remove "category" so we don't see "category: null" and "invalid date"?). Jeremy thinks this issue (comments above) would fix this, at least the rendering of the YAML frontmatter.
<img width="942" alt="12" src="https://user-images.githubusercontent.com/899033/48786372-be8d4d80-ecb4-11e8-92e6-a20af9835db7.png">
