### ISSUE TITLE
Tweak events display in search results

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#541]
Currently displaying metadata oddly (e.g. remove "category" so we don't see "category: null" and "invalid date"?)
<img width="942" alt="screen shot 2018-11-19 at 12 34 40 pm" src="https://user-images.githubusercontent.com/899033/48724639-c33ffc00-ebf7-11e8-9302-444b86c7f06f.png">

the display gets built in `assets/js/search.js`

these lines in particular determine the HTML structure of each result - https://github.com/scholarslab/scholarslab.org/blob/master/assets/js/search.js#L32-L79

**Comment by jeremyboggs** [comment]
This is a big issue with building the search corpus by reading the Markdown directly, instead of having Jekyll build it. Fixing #539 would address this, at least the rendering of the YAML frontmatter.

**Comment by amandavisconti** [comment]
Cool, I'll add a note on #539 and close this!
