### ISSUE TITLE
Spatial Tech page, Phase 2

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#570]
Update: @jeremyboggs created https://github.com/scholarslab/chi, e.g. https://scholarslab.github.io/chi/records/corinthian-kotyle/

Amanda and Laura met 2/19/2019, will pursue the following work using the `spatial-tech-rocks` [branch](https://github.com/scholarslab/scholarslab.org/tree/spatial-tech-rocks):
- [x] Test 3DHOP integration
- [ ] Consider adding Virgo search box filtered to Will’s 45+ #lib3dchi datasets using [this documentation](https://confluence.lib.virginia.edu/pages/viewpage.action?pageId=129441357)
- [ ] You can also add a Dataverse widget on the SLab site for the #lib3dchi datasets. This shows a mini version of the Dataverse sub-collection: <script src=“[https://dataverse.lib.virginia.edu/resources/js/widgets.js?alias=culturalheritage&amp;dvUrl=https://dataverse.lib.virginia.edu&amp;widgetScope=culturalheritage&amp;widget=iframe&amp;heightPx=500](https://dataverse.lib.virginia.edu/resources/js/widgets.js?alias=culturalheritage&dvUrl=https://dataverse.lib.virginia.edu&widgetScope=culturalheritage&widget=iframe&heightPx=500)”></script>
- [ ] Look for text drafted via previous Spatial Tech unit meeting (GDoc?)
- [ ] Create subpages
- [ ] Twitter feed (maybe just Will's tweeted photos? maybe just when RT'd by SLab account?)
- [ ] #439 adds links to SLab in the News; pull SpIn-specific news into their unit page as well?
- [ ] Pull /work projects into main SpIn page (filter to projects that use 1+ SpIn staff names, and don't have the metadata `display-on-unit-subpage: no`
- [ ] Add the metadata `display-on-unit-subpage: no` to projects including SpIn staff that shouldn't be pulled into the SpIn unit page as representative of SpIn work (e.g. Praxis)
- [ ] Create /pages/folder containing new CHI and GIS subpages
- [ ] Fill out CHI subpage: mission / description; tools - details (photos/documentation); data links
- [ ] Fill out GIS subpage: Map databases (see libguide); Link to software downloads; Course teaching tools; aerial photos  
- [ ] prototype including datasets + student portfolios

Once above tasks complete:  
- [ ] Schedule us to show updates/prototypes to Spatial Tech team at next SpIn unit meeting
  - [ ] Their preferred approach: just a portal to your existing webpages/Libguides, do something different than those, have the same content (but add things you can't currently do with those spaces), something else?

**Comment by jeremyboggs** [comment]
I can help with 3DHOP integration.

**Comment by amandavisconti** [comment]
Scheduled time to work on this 5/30
