### ISSUE TITLE
Find Us Map and Colorings Mismatch

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#579]
Between 400 and 600 px the "Find us" colorings don't match the map.
<img width="625" alt="screen shot 2018-11-30 at 4 48 31 pm" src="https://user-images.githubusercontent.com/2334220/49316726-d8ead680-f4bf-11e8-922b-c8e111db4fe3.png">

**Comment by walshbr** [comment]
I just realized this was all going to be obsolete once Alderman was under renovation anyway, so I'll put a pin in this for now.

**Comment by amandavisconti** [comment]
Note this now appears on two static pages, so should check any CSS fixes work on both:
- [ ] scholarslab.org
- [ ] scholarslab.org/hours-and-spaces

**Comment by amandavisconti** [comment]
Closed because we're moving out in May
