### ISSUE TITLE
Some post citation info sections w/o image

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#581]
Citation section at bottom of every blog post should show author's image.

Beth's shows default image (http://maybe.scholarslab.org/blog/call-for-applicants-dhsi-2019-tuition-fellowships/), so we know it's working for some folks without an associated photo

But Kelli and Emily' posts don't show an image: http://scholarslab.org/blog/starting-off-on-the-right-foot-part-one/ and http://scholarslab.org/blog/sounding-scholarship-a-workshop-on-making-your-research-sing/

**Comment by walshbr** [comment]
IIRC, that's actually because the default image there was actually called beth-mitchell for a while, because we didn't have a photo for her. So that means…
1. it's not working at all for default photos
2. the naming of that photo didn't get switched over, which is easy to do.

I can take a look.
