### ISSUE TITLE
Fix 3 blanks in event-creation documentation

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#588]
I can't remember who set up our event YAML format and how it works with @jeremyboggs' fix for moving events from “upcoming” to “past”—could that person look at [my documentation for adding events](https://docs.google.com/document/d/1qLncvRa6aqQPpf2BtZwGJFf_vqrLTG6EB6qoyenZxLc/edit?usp=sharing) and fix the three places I've commented there? Thanks!

- [ ] Wasn't sure what `all_day` should use when it isn't `null`  
- [ ] how the `published-date` is used (if at all)  
- [ ] whether `rsvp` uses a `1` if a RSVP is required (and whether that is still set up to place an RSVP request on the events page)

**Comment by walshbr** [comment]
@amanda I believe all_day should only ever be 0 and 1. I think null is just something we haven't filled in, but it's also literally never called once so it hasn't produced any errors. I'm not sure exactly what the idea was behind it, but that field isn't being used presently.

published_date is never used.

And that's how i read rsvp as well. But, again, that's a field that is never used. I think those are fields from the WP metadata that were never really used.

**Comment by amandavisconti** [comment]
Dropped all_day, published-date, & rsvp metadata fields, as these are not tied into anything that changes on the site. Checked site first to see if these are called anywhere.

**Comment by amandavisconti** [comment]
@walshbr Will it break anything if I remove those 3 metadata fields (all_day, published-date, & rsvp) from the rake new-event task?
