### ISSUE TITLE
Migrate People Photos

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#59]
Have successfully migrated the people files, but there are a number of photos associated with them that need to be migrated from wordpress.

- [x]  Ankita Chakrabarti
- [x]  Victoria Clark
- [x]  Spyros Simotas
- [x]  Ryan Maguire
- [x]  Julia Haines
- [x]  Sarah Berkowitz
- [x]  Lauren Reynolds
- [x]  Ben Gorham
- [x]  Katherine Donnally
- [x]  Catherine Addington
- [x]  Brandon Phan
- [x]  Nic Dalton
- [x]  Andrew Carl
- [x]  Marysia Serafin
- [x]  Zoe LeBlanc
- [x]  Elizabeth Mitchell
- [x]  Tanner Greene

**Comment by jeremyboggs** [comment]
@walshbr Can you make some time to work on this? Or discuss here further?

**Comment by walshbr** [comment]
kk - just involving taking the large photo assets from wordpress and dropping them in the associated assets/people folder here?

**Comment by walshbr** [comment]
These people were using stock makerspace photos. I brought their stock photos over anyway, but just thought it should be noted somewhere that we don't actually have photos of them.

- [ ]  Catherine Addington
- [ ]  Brandon Phan
- [ ]  Nic Dalton
- [ ]  Andrew Carl
- [ ]  Marysia Serafin

Similarly, these two people don't have photos. But they also don't have stock makerspace photos. 


- [ ] Elizabeth Mitchell
- [ ] Tanner Greene

So I just randomly chose some stock photos for them as placeholders. But if we want real photos we should get in touch with @shane-et-al.

**Comment by walshbr** [comment]
Closed in #184
