### ISSUE TITLE
Make citation easy

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#6]
Info on how to cite each blog post and project on appropriate page

**Comment by jeremyboggs** [comment]
This could be handy to also generate meta elements for citations managers (e.g. Zotero) to use.

**Comment by amandavisconti** [comment]
Added to _layouts/post.html in footer.
- [ ] check that works for multiple authors
- [ ] Accessed on date?
- [ ] Add to all pages? Just to project pages?
- [ ] generate meta elements for citation managers?

**Comment by jeremyboggs** [comment]
I think this is worth us composing an example, of what it would look like, what content it would have, and where it might go. Most of this _should_ be generated from the post/page metadata in the YAML frontmatter.

**Comment by amandavisconti** [comment]
Added accessed-on date.

**Comment by amandavisconti** [comment]
the date published is listed as '02/28/2018' but the access date is formatted as 'May 23, **18'**

**Comment by jeremyboggs** [comment]
This will need to be rendered in JavaScript to get today's date. The liquid stuff is just generating whatever date is current as of the build.

**Comment by amandavisconti** [comment]
I'm sure this can be done more concisely (in particular, not duplicating the same code if the post doesn't have an author).

Moving "generate meta elements for citation managers" to Rainy Day milestone.
Moving citation on project pages to separate issue.
