### ISSUE TITLE
Update our frontend config set-up

### ISSUE THREAD

**Issue by ZoeLeBlanc** [scholarslab/scholarslab.org#61]
### Context
1. What should the feature do?
This feature should integrate webpack and yarn into our set up for our jekyll site. The rationale is to prevent node module dependency errors and to use a dependency compiler so our javascript and css files can be required into each other, instead of global variables
2. When and where should the feature appear?
This will impact the root folder and our dev setup

**Comment by jeremyboggs** [comment]
@ZoeLeBlanc Is this something that still needs to happen? If so, what are our next steps? What would webpack and yarn do, respectively?

**Comment by ZoeLeBlanc** [comment]
@jeremyboggs yarn is more necessary than webpack though both are useful. Essentially they help manage front end dependencies and bundle JavaScript. These are both somewhat dependent on search functionality which I’m not sure of it’s current status. Let me know if search needs to be rebuilt at all or if Katherine has it covered
