### ISSUE TITLE
Create page redirects for 11 broken pages

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#615]
See below

**Comment by amandavisconti** [comment]
@jeremyboggs I have the full list of broken /makerspace links now, below:

https://scholarslab.org/makerspace/raspberry-pi-on-uva-wifi-network/
http://old.scholarslab.org/makerspace/makerspace-3d-printer-calendar/
http://scholarslab.org/makerspace/fall-2018-maker-code-workshop-series/
https://scholarslab.org/makerspace/hack-your-pants-video/
https://scholarslab.org/makerspace/1st-annual-makerspace-hackontest/
https://scholarslab.org/makerspace/3d-printing-for-fun-and-presentation/
https://scholarslab.org/makerspace/3d-printing-in-the-classroom-outcomes-and-reflections-on-a-slavic-course-experiment-22/
https://scholarslab.org/makerspace/3d-printing-in-the-classroom-outcomes-and-reflections-on-a-slavic-course-experiment-12/
https://scholarslab.org/makerspace/saving-arduino-sensor-data/
https://scholarslab.org/makerspace/bigger-nozzles-faster-printing/

**Comment by jeremyboggs** [comment]
@amandavisconti These should be fixed; Can you help me confirm each?

**Comment by amandavisconti** [comment]
@jeremyboggs Thank you! I'll check each and let you know if any don't work.

**Comment by amandavisconti** [comment]
Only one is weird:  
http://scholarslab.org/makerspace/makerspace-3d-printer-calendar/  
should instead go to https://scholarslab.org/makerspace/#calendar-link


(currently, the redirect is just replacing /makerspace/ with /blog/)
