### ISSUE TITLE
Create starter pack on working with text

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#63]
Questions to think through when embarking on text-based projects (editions in particular, but possibly also expand to support text analysis questions with assistance from others?)

How do you get that text?
Copyright, non-consumptive use
Scanning vs. manual input, OCR, OCR correction, formatting/style
annotation/metadata around physical book+page
markup of text and physical book+page

**Comment by walshbr** [comment]
Happy to help put together a non-consumptive / text mining portion for this

**Comment by amandavisconti** [comment]
Some initial text up, but not at all ready to be treated as a draft: https://github.com/scholarslab/scholarslab.org/blob/master/_starter-kits/text.md

**Comment by amandavisconti** [comment]
We can search for and reopen "starter kit"-related issues if anyone ever wants to make these happen
