### ISSUE TITLE
Inconsistent Black Backgrounds

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#635]
Main page the header nav bar is the same color black as the rest of the background.
![screen shot 2019-01-08 at 4 42 52 pm](https://user-images.githubusercontent.com/2334220/50860659-81fcda80-1364-11e9-8659-043da96afadc.png)

On all other pages it's a slightly different shade.
![screen shot 2019-01-08 at 4 42 55 pm](https://user-images.githubusercontent.com/2334220/50860664-85906180-1364-11e9-8ae7-7fe1759b4626.png)

My inclination is to keep the two shades consistent across all pages. But #586 might affect this. If this is expected or fine this can just be closed.

**Comment by amandavisconti** [comment]
May be addressed by retheme; closing this ticket and referencing in #1001 (lists old theme issues that could be addressed/mooted by retheme; with note to reopen those issues if they are still problems at that point)
