### ISSUE TITLE
Documentation for front-end contribution

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#64]
### Context
1. What should the feature do?

-Provide written evidence of processes used to build site.
-Serve as guide for future changes to site once is > 0.x version.
-Examples: steps to change language on given page, CSS class-naming guide.

2. When and where should the feature appear?

-As relative `.md` link within README.

### Expected Result
*In a perfect world...*

-Standardized way to update the site, and standardized way to universally let everyone know if our updating processes have changed (i.e., if said documentation changes). 
-No one wonders whether they're doing things the right way, and we avoid a lot of issues related to conflicting CSS names and contribution workflow.

**Comment by kbdonnally** [comment]
Partially addressed w/ PR #77 --> content contribution discussed, style contribution still unaddressed.

**Comment by amandavisconti** [comment]
Moved off this milestone as isn't dealbreaker for public launch of site
