### ISSUE TITLE
Get rid of white strip on black-background pages

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#644]
From @walshbr on https://github.com/scholarslab/scholarslab.org/pull/634:

The only thing I notice is that it's inconsistent across different pages that have different design backgrounds. Is that intentional? Or did you want to get rid of the white strip on the black background pages?

This is a typical white background - 
![screen shot 2019-01-07 at 2 43 51 pm](https://user-images.githubusercontent.com/2334220/50789645-ddf33080-128a-11e9-82a3-77ea762ac548.png)

This is a page with a black background, like the makerspace - 
![screen shot 2019-01-07 at 2 43 43 pm](https://user-images.githubusercontent.com/2334220/50789646-ddf33080-128a-11e9-807e-c6f192616c99.png)

**Comment by jeremyboggs** [comment]
This should be fixed in 61f3770 and 9c0bf9c.
