### ISSUE TITLE
Figure out exactly how post timestamp vs. display time work in Jekyll

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#656]

**Comment by jeremyboggs** [comment]
@amandavisconti Unless you're looking for something more specific as it relates to our site, you can check out the various `date` filters in [Jekyll](https://jekyllrb.com/docs/liquid/filters/) and in [Liquid](https://help.shopify.com/en/themes/liquid/filters/additional-filters).

**Comment by amandavisconti** [comment]
I think this might be separate—those filters just deal with presentation of date, don't they? Sorry, this was a note to myself so I neglected to provide that detail!

Actually think dropping time from all post's date YAML fixes this; I'll test whether we can do that with posts going forward without breaking anything, then update the documentation/post GDoc template to match. I'm guessing we can always include time as part of the YAML if we care about the order of multiple posts published on the same day.

Original ticket reason was from several times having trouble where depending on a post's front matter date/time, the post wasn't published when the site builds (like, I'd told folks learning to blog on the site to just use 01:00:00 as the timestamp on their new posts, but am not sure the timezone the front matter assumes vs. the timezone the site build uses and that sometimes led to posts not appearing if the site build thinks the current time is before the post YAML time).

**Comment by amandavisconti** [comment]
Added a note to myself to test this next time I publish a blog post.
