### ISSUE TITLE
Post category & tag metadata bamboozle

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#659]
- [ ] Scrape all posts to see what categories and tags are already in use?
- [ ] Decide which ones we currently want to use
- [ ] Check where/how categories and tags are used in the site, e.g. eyebrow tags, to create pages we had on the old website and thus still need (e.g. page of all "makerspace" tagged posts)
- [ ] Work through all posts in past 2 years and update their metadata
- [ ] Work through all posts from over 2 years ago and update their metadata
- [ ] Update posts template so everyone can see which categories and tags we can use: https://docs.google.com/document/d/1OWBTybWrpZuesu8BQVQTbpXMkIC5p-nyAW26DV7r_A4/edit?usp=sharing
- [ ] Also create template post draft in /_collections, if this doesn't mess site display up?

**Possibilities:**
_categories:_
- Digital Humanities
- Research and Development
- Announcements
- Job Announcements
- Makerspace
- Grad Student Research
- Podcasts
_tags:_
- Digital Humanities

Need to have:
Neatline
Tutorials

**Comment by walshbr** [comment]
Note that I have added some student project related tags (mainly to distinguish the Praxis projects from one another). I'm using those in the project archive.

**Comment by amandavisconti** [comment]
Scheduled time to work on this week of 6/3

**Comment by walshbr** [comment]
Have also been using "Parents Fund" to mark the PF posts.

**Comment by amandavisconti** [comment]
See also closed #270

**Comment by amandavisconti** [comment]
See new list pinned in Slack year-of-the-blog channel too
