### ISSUE TITLE
Subdomain redirects

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#670]
http://spatial.scholarslab.org/stepbystep/online-gis-using-arcgis-com/ was [highlighted](http://digitalhumanitiesnow.org/2012/08/resource-online-gis-using-arcgis-com/) by DH Now, but no longer points at a thing

@lam2c or @gitdrewmac, if you know where this resource now lives, let me know and I'll set up a redirect so the DH Now page still points at it? Thanks! (Zero hurry on this...)

**Comment by jeremyboggs** [comment]
It's at spatial.scholarslab.org/online-gis-using-arcgis-com/. We should redirect it, if possible.

**Comment by gitdrewmac** [comment]
Sorry, just seeing this. My git account points to my spammy hotmail email addy, and I missed it. I'll change to a more useful email address.
