### ISSUE TITLE
*After time passes*, remove old.scholarslab.org WP site from server

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#678]
Wait until June 2019 (or checking in with staff on #slab-org Slack channel or by email) before:

We switched to the new static site in January 2019, and content export plus backup of the Old.ScholarsLab.org site are in a [private repo](https://github.com/scholarslab/slab-org-pre2018) if needed. Once we don't think we'll need admin dashboard access to the WP site anymore (June 2019, maybe?) let's remove it from our servers so we don't need to deal with security/maintenance issues.

**Comment by walshbr** [comment]
I think it's worth keeping the site up at least through the great markdown syntax cleaning of 2019, which I'd like to do this summer. I had to go in and just copy some HTML from an older post that had blockquotes butchered in the migration.

**Comment by walshbr** [comment]
Whoops! closed the wrong one
