### ISSUE TITLE
Nightly site rebuild?

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#679]
To make the site show upcoming events correctly (i.e. not ones that have past)

**Comment by jeremyboggs** [comment]
@amandavisconti Can you add more detail to this? How should we display our events differently? I thought we had actually addressed this before launch.

**Comment by amandavisconti** [comment]
This is minor or possibly wont-fix, but now that we don't have folks pushing to master every day:

The website homepage lists upcoming events, which makes it look like it's the next upcoming event + events after that. But because no one had pushed to master since a few days earlier, last Thursday it still looked like workshops earlier in that week were upcoming (when in fact they were past), with Alex's events not happening until after those past events (when in fact they were our next events to occur).

Events on the homepage do show their correct dates, so anyone paying attention would quickly see that e.g. that Tuesday workshop had already happened. But only a couple of the upcoming events appear on the homepage, so this can push events that are in fact happening (or happening next) off the homepage. And it's possible that folks scanning the homepage events list might stop after seeing the top event has already happened, and not read any further?

**Comment by jeremyboggs** [comment]
@amandavisconti We discussed Ammon implementing a nightly build cron job on the server. Regardless of wether we push to master, that job will rebuild once per night. @ammonshepherd When you have that working, just close this ticket.

**Comment by jeremyboggs** [comment]
This is implemented. Thanks @ammonshepherd
