### ISSUE TITLE
List Previous Events only if in the past 

### ISSUE THREAD

**Issue by lam2c** [scholarslab/scholarslab.org#683]
events page issue: all the 2019 events are listed in the 2019 "previous events" list, whether they have happened yet or not (i.e. not just the past ones).

**Comment by jeremyboggs** [comment]
@lam2c I'll submit a patch that will list only events that occurred prior to the current date.

**Comment by jeremyboggs** [comment]
Related to this, it seems our code currently treats events _today_ as previous events, and not current events. I'll update our listings to ensure events for the current day are still treated a current events.
