### ISSUE TITLE
Fix weird right padding on text under hero text

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#706]
<img width="1507" alt="screen shot 2019-03-07 at 1 24 07 pm" src="https://user-images.githubusercontent.com/899033/53979673-74ea3680-40dc-11e9-922e-c2e30853cab0.png">

**Comment by jeremyboggs** [comment]
Wasn't there an image or something to the right of this content?

**Comment by jeremyboggs** [comment]
I'd probably recommend combining the text under *What We Do* and *Explore With Us* into one section, either under one of those headings or without a heading. Any preferences?

**Comment by amandavisconti** [comment]
Combining sounds good; I'm currently leaning toward "what we do" (to make that easy to understand), but am good with either header being used. 

I don't think there was an image there? I'm not sure what could work there—a photo of the Common Area space? People collaborating, maybe on Praxis?

There's one lower on the page, near the student section.

**Comment by walshbr** [comment]
There was no photo there that I remember. I can take a swing.
