### ISSUE TITLE
Add student projects to student project archive

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#742]
- Jean Bauer  
- Jen Grayburn
- Ed Triplett

**Comment by walshbr** [comment]
I couldn't find adequate evidence of their projects on the blog to be able to describe them, FWIW. But it would great to add them if you feel more confident in knowing where to look or can point me in the right direction.

**Comment by amandavisconti** [comment]
I Slacked to see if anyone remembers something about these projects!

**Comment by amandavisconti** [comment]
Closing because we don't have the info to add these
