### ISSUE TITLE
Failing builds due to unknown tag

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#757]
We're getting a "page build error b/c the tag 'markdown' is not recognized" whenever we push to master. This is because the markdown tag is one I put together to process markdown explicitly even when it was inside closing divs here - https://github.com/scholarslab/scholarslab.org/pull/736. GitHub pages doesn't accept plugins in that way, which is why we're getting an error. But we're not actually using GitHub pages anymore for this repo - that's just an artifact of development, I believe. We should be able to disable this, but as best I can tell it wants us to _delete the master branch_ in order to do so, which seems awfully wild and extreme. I'll investigate further, but flagging it here @jeremyboggs in case you wanted to take a look. Mostly didn't want us to forget about it.

**Comment by jeremyboggs** [comment]
Yup, @walshbr, this is rather silly on the part of Github. I got around this by 1) changing the publishing source to the `gh-pages` branch, and 2) deleting said `gh-pages` branch. We are now no longer publishing the site using Github pages; I also removed the CNAME file in 2c5fc62.

**Comment by walshbr** [comment]
Wooow what a silly fix. I'm glad you got it sorted! Thanks @jeremyboggs
