### ISSUE TITLE
Add photos of students for 2019-2020 Cycle

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#763]
We need:

- [ ] Photos for DH Fellows
- [ ] Photos for Praxis Fellows
- [ ] Photos for Parents Fund students
- [ ] Makerspace techs

**Comment by jeremyboggs** [comment]
@walshbr This seems like something we should get done before the end of the Fall semester. Are there any blockers for this now?

**Comment by walshbr** [comment]
The checklist is correct @jeremyboggs - we have people pages with placeholder images all public. We just need photos from @shane-et-al to close out this.

**Comment by walshbr** [comment]
I'll update the title to reflect the state it is at.

**Comment by walshbr** [comment]
Got the photos from Shane for those students who showed up for a photoshoot. I'll put out another call in the spring for makerspace techs and stragglers, but this is only an opt-in thing after all. So I think we've gotten the photos we're going to get for now.
