### ISSUE TITLE
Standardize the Way Posts are Crossposted

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#767]
Currently being done a thousand different ways. Let's make it a YML field / include.

**Comment by walshbr** [comment]
Whatcha think @jeremyboggs? This takes a yaml field "crosspost" and, if it's there, generates that little bit with whatever is in it. A little clunky because you have to escape double quotes and code the link yourself in the include, but there were enough edge cases that I couldn't think of a way to cleanly do it in an accessible way. Some people crossposted to multiple places, some people editorialize, etc. And just listing "crossposted here" seems inaccessible. This allows the pull quotes for the blog page to work properly.

<img width="894" alt="Screen Shot 2019-06-24 at 2 11 57 PM" src="https://user-images.githubusercontent.com/2334220/60041710-0f6d8600-968a-11e9-8947-850274909f60.png">

**Comment by jeremyboggs** [comment]
@walshbr it'd probably be cleaner to structure the YAML like so:

```
---
crosspost:
  - title: W&L DH Blog
    url: https://example.com
---
```
This would seem to have a couple of advantages:
- You don't need to properly code the link tag itself;
- You could easily have multiple crossposts.

**Comment by jeremyboggs** [comment]
@walshbr When you say "a thousand different ways" do you have a sense of which posts currently have crossposts elsewhere? Regardless of how they crosspost, we maybe should review those and update them with our new crossposting approach.

**Comment by walshbr** [comment]
@jeremyboggs When i did my search in Atom yesterday, there were about 100-110 instances of "crosspost" or "cross-post" that came up. 1000 was an exaggeration. :) 

That makes sense to me. Do we care about losing the context/editorializing some people do when they crosspost? Katina and the W&L blogs seem to be the main ones - 

"Enjoy this guest post by Sam Lemley and Neal Curtis, graduate students in English at University of Virginia. They came to W&L to give a workshop in Prof. Holly Pickett’s sprint-term “Othello, Ourselves: Race, Religion, and Reconciliation in Shakespeare” course through a Mellon-funded collaboration with the Scholars’ Lab at UVA. More information about this initiative can be found here. Crossposted to the W&LDH blog."

I guess we could do something like…
---
crosspost:
  - context: blah blah blah blah blah blah
    title: W&L DH Blog
    url: https://example.com
---

Check to see if there is a context for the crosspost. If there is, stick it in before the URL linking. If not, just do the URL linking. That seem like it would work?

**Comment by jeremyboggs** [comment]
@walshbr There seems to be a lot more going on in this example that just crossposting. Multiple authors, who are guest authors (and presumably didn't have authoring privileges in our WP instance), with the posting author providing a contextual introduction to the post. This seems a separate thing to tackle from actually encoding a _crossposting_, and I'd suggest we do that in a separate commit, with a separate but possibly related solution.

**Comment by walshbr** [comment]
That does make sense, and I think that we can probably just say that such editorializing should be considered post of the content anyway. I think I can act on this - thanks!

**Comment by jeremyboggs** [comment]
> I think you're right about the piece about author privs. I'll open a separate ticket for that - it seems like we could just handle that by making those folks people pages and being done with it.

We don't even need to do that; Just listed them as a post author, using "FirstName LastName" as a string instead of a "firstname-lastname" identifier. There are some examples of this.

I bring it up becuase the example seems to be explaining why this is crossposted, and who the actual authors are. But now pretty much anyone can be an author now, or at least listed as one.

**Comment by amandavisconti** [comment]
@walshbr I can't remember—can we merge the PR and close this issue?

**Comment by walshbr** [comment]
Hmm…I think the only reasons not do would be:

a) it's a new blogging feature not mentioned in the docs
b) more recent blog posts don't use it, so we'd need to look at the last few months of posts for any crosspostings and update them. 

But I think we could merge it and open those two things as new issues.

**Comment by amandavisconti** [comment]
@walshbr Cool! Thanks for making this happen. I'm going to merge and will open separate issues for those two things.
