### ISSUE TITLE
Check if retheme mobile testing addressed past mobile under/overfilling containers

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#787]
On mobile, the header and footers aren't filling the screen width. (Because?) The body is pushing running off the screen width as well.  Amanda's recent blog post is an example.
![Screen Shot 2019-07-01 at 9 46 34 AM](https://user-images.githubusercontent.com/2334220/60441511-23167080-9be5-11e9-9e6f-84e8b9cb409c.png)

**Comment by jeremyboggs** [comment]
@walshbr Can you say how you encountered this? Safari on a iPhone? Something else?

**Comment by walshbr** [comment]
Yeah - safari on iphone for that particular blog post gives an example of it.

**Comment by jeremyboggs** [comment]
Yup, i see it now. and i see it on a few others. But not all the posts. So...why this is only happening on _some_ will be a fun thing to figure out.

**Comment by walshbr** [comment]
haha For that one at least I wondered if it was the image sizes (never did feel like we had a good way to handle responsive image sizes).

**Comment by amandavisconti** [comment]
May be addressed by retheme; closing this ticket and referencing in #1001 (lists old theme issues that could be addressed/mooted by retheme; with note to reopen those issues if they are still problems at that point)
