### ISSUE TITLE
Create layout for starter kit pages

### ISSUE THREAD

**Issue by kbdonnally** [scholarslab/scholarslab.org#80]
### Context
1. What should the feature do?
- We want to create learning pages to cover the basics of some DH-type topics. We've been referring to these as "starter kits". It's a new page, so it'll need a layout created.
- Create HTML template to use for eventual content of starter kit pages.
2. When and where should the feature appear?
- In `_layouts/` directory

**Comment by amandavisconti** [comment]
We can search for and reopen "starter kit"-related issues if anyone ever wants to make these happen
