### ISSUE TITLE
Update Blogging Documentation to account for branches on branches

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#818]
“B. If you’re Totally Ready to Publish your new blog post, instead switch the radio button to “Create a new branch for this commit and start a pull request”, leave the text field that appears as-is, and click the green “Propose new file” button. Jump down this tutorial to Section 2, which covers what to do next now that you’re ready to publish.”
it all works fine if they’re working on a file for the first time. but if they’re going back to edit the file a second/third/etc. time, they need to be sure that they are committing their changes to the original branch that they created (the first radio button) and not the second radio button (which will create a new branch). i’m not exactly sure where to add that in the documentation

**Comment by amandavisconti** [comment]
Fixed!
