### ISSUE TITLE
Meet w/SpIn team to discuss their website needs

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#83]

**Comment by amandavisconti** [comment]
Scheduled!

**Comment by lam2c** [comment]
this is public service - mind if I attend?  or i can schedule my own meeting, if you'd rather.

**Comment by kbdonnally** [comment]
What does this issue mean?

**Comment by amandavisconti** [comment]
@lam2c @kbdonnally I hadn't scheduled a thing—this was more a reminder for all of us that Will asked during a previous (March?) all-staff meeting when Spatial Tech would have a chance to discuss how they want to be represented (on the front page and on a new Spatial Tech page. I think I created this to be sure that discussion was scheduled. This ticket is maybe redundant with #96, #45, #75 ?
