### ISSUE TITLE
Open access commitment on homepage

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#866]
Please leave this issue for Laura and Amanda to work on.

Add language about our commitment to open scholarship on our front page somewhere

**Comment by jeremyboggs** [comment]
The commitment text might need to consider/explain the removal of the CC-By license in 7589a7e6eccb2d2d2949a148c2e27a12efda9314.

**Comment by amandavisconti** [comment]
Agree. I'm closing this now as I've moved it to a comment on our about page text in the GDoc (current plans for homepage don't have space for this, what this text is unclear, can't work on it until finish publishing updated website this summer).
