### ISSUE TITLE
SVG support error

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#869]
![Screen Shot 2020-03-15 at 11 34 44 PM](https://user-images.githubusercontent.com/899033/76721201-96c9c080-6715-11ea-8463-614fd3d6ddf4.png)

Seen on Mac Firefox 73.0.1 on 3/15/2020

**Comment by jeremyboggs** [comment]
@amandavisconti I can't replicate this, using the same version of Firefox on Mac. Could you confirm this?

**Comment by amandavisconti** [comment]
I'm on 74.0 now, but can't replicate, so will close this
