### ISSUE TITLE
Update website for Clemons during renovation, remote services, and main library renaming

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#880]
We're no longer in Alderman, so they're inaccurate. Technically I guess we could switch to Clemons maps…but I'm not exactly sure how these were designed. They're great to have, but not sure we have the expertise (unless @jeremyboggs knows how to wire them together). I'm inclined to just remove them until such time that we have a designer. And maybe replace them with some text.

**Comment by amandavisconti** [comment]
- [ ] Remove "Find Us" Maps from front page
- [ ] Rename "Alderman" to "main library" or "main library (formerly known as Alderman)*" with link to info on renaming reason  
- [ ] Hours & Spaces update (including maps, photos, directions)
- [ ] General scan of site for mentions of Alderman, Clemons, where to find us, spaces/equipment/hours changes, remote services changes, etc.
