### ISSUE TITLE
Add New Students for Fall 2020

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#886]
I added all the fellows as they currently stand for the DH fellowship and Praxis. Still need these categories of students for the fall: 

- [ ] Makerspace students
- [ ] CHI interns
- [ ] GIS students

My sense is that the budgetary uncertainty means we don't know the status for those students yet. Pinged Shane to ask what he wanted to do about photos this semester. I suggested they just send in their own headshots if they have them for now.

**Comment by ammonshepherd** [comment]
We only have three returning students; Andrew, Nora and Brandon.

**Comment by walshbr** [comment]
Done!
