### ISSUE TITLE
Update text on accessibility page

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#9]
After #217 
Design and testing

**Comment by jeremyboggs** [comment]
FYI: on our [Accessibility](http://scholarslab.org/about/accessibility/) page, we state that we adhere to WCAG 2.0 and Section 508 guidelines.

**Comment by amandavisconti** [comment]
http://accessibility.voxmedia.com/

**Comment by amandavisconti** [comment]
Possibly useful ideas from a related ticket I closed:
Inspired by @rondauva sharing [thread](https://twitter.com/alexhaagaard/status/1119385219033903104?s=20) on accessibility that goes beyond step free access and screen readers, do we want to improve our /accessibility page (https://github.com/scholarslab/scholarslab.org/issues/9) to be about more than the website's accessibility (e.g. reminders, suggestions, best practices for events, social media renovation, daily practices, etc.?)

    @jeremyboggs & @rondauva on podcasts/recording+captioning/transcribing
    @ammonshepherd links toward Makerspace accessibility:
        https://www.washington.edu/doit/making-makerspace-guidelines-accessibility-and-universal-design
        https://www.unitedspinal.org/pdf/DisabilityEtiquette.pdf
        https://ada.osu.edu/designguidance/disability%20ettiquite.pdf
    DLF and other existing resources

Re: https://github.com/scholarslab/scholarslab.org/issues/9, https://github.com/scholarslab/scholarslab.org/issues/217 other explicit web accessibility tasks (https://github.com/scholarslab/scholarslab.org/issues/548, https://github.com/scholarslab/scholarslab.org/issues/526, https://github.com/scholarslab/scholarslab.org/issues/519).
