### ISSUE TITLE
Upgrade Ruby Version

### ISSUE THREAD

**Issue by walshbr** [scholarslab/scholarslab.org#925]
I just got a new work laptop - M1 running Big Sur. After some searching around and troubleshooting, it looks like M1 machines don't support versions of ruby before 2.7.2. So we might consider upgrading our ruby version? If I'm the only one this will affect I can just try to find a workaround. It looks like they exist but they were getting a little too in the weeds for me to feel comfortable doing on my own. Would need to work with Shane on it probably.

**Comment by jeremyboggs** [comment]
This has been done in 6502014d972c037913c3595c8f4695b1d0974c26.
