### ISSUE TITLE
Ask Shane to investigate our making this repo private (ie server hook needs auth info?)

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#985]
Want to make this repo private before more theming work, to avoid future sites exactly reusing our theme and much of our text like one external project already did.

**Comment by amandavisconti** [comment]
rolling into #992

**Comment by jeremyboggs** [comment]
I'd like to put in a vote for keeping our repo public, as part of our own Lab mission of doing and sharing our work in public for the benefit of others.

**Comment by amandavisconti** [comment]
I might be okay with that also, if we could put clearer licensing and credit text on things? I think my two concerns were: 
1) having another DH site with exactly our design/colors (confusing about our relation to them, makes our site look unoriginal, maybe these aren't actionable emotions though) and 
2) seeing our mission/about text largely copied without attribution (anyone can copy text, but forking makes it easier/more tempting to just tweak text that already sounds good to you; again, maybe not a good reason to restrict repo access)
