### ISSUE TITLE
Removed pages needing redirects

### ISSUE THREAD

**Issue by amandavisconti** [scholarslab/scholarslab.org#993]
I removed the following pages from the /realignment branch.

These pages should get a redirect somewhere, since they are conceivably linked elsewhere:
1. accessibility (could move into charter or about page. _reason for removal:_ page content is stale needs update _after_ web sprint that describes current site accessibility work; ask Ammon for details of how makerspace is now more accessible; pandemic-accessible events)
2. blogging (redirect to the /work collection item I created; I also added the page content that was on /blogging to the blog post that was just a brief pointer to that blogging page)

These removed pages can stay without a redirect (404 page feels sufficient?):
4. library (moved into /about answer text)
5. search (removed)
6. sitemap (removed)

**Comment by jeremyboggs** [comment]
Why is `search` removed?

**Comment by amandavisconti** [comment]
> @amandavisconti We also need to confirm whether deploying to Github using Actions will allow us to also have page redirects.

I've added a note on #992 to test redirects as necessary to the GH Pages/Actions workflow plan (will start by testing Jekyll redirect plugin, which I believe I use with other Jekyll sites hosted on GH pages fine already)

**Comment by amandavisconti** [comment]
> Why is `search` removed?

The plan for if we do move ahead with shifting site building and deployment to GH Pages/Actions (couple things to investigate first, in #992) is to temporarily remove site search. We'd explore readding it at some later point after the current sprint's goals are all done, if someone has time/interest. (See my 6/13 email checking this was okay with you/Shane/Brandon for details.) 

Since we wouldn't have the function, I removed the page. (Sounds like we might be interested in omving a search field into e.g. the header if we do return to it, since folks weren't aware of/using it given it was buried deep in the menu before?)

**Comment by amandavisconti** [comment]
Updated [initial issue content](https://github.com/scholarslab/scholarslab.org/issues/993#issue-2353986052) to specific we only really need to redirect 2 of these.

**Comment by amandavisconti** [comment]
This was all done as part of #992; closing
